### ISSUE TITLE
Location and pokestops

### ISSUE THREAD

**Issue by k2sapex** [finndev/PokeBuddy#100]
When i put the location in Central Park, the bots all the time show the message "Populating Pokestops" and dont catch pokemons but if i go to Germany is all good can you fix it? Central Park is a good location   Thanks!

**Comment by Vanethir** [comment]
Unfortunately I don't think we can solve this issue on PokeBuddies side.
Niantic probably uses location based servers. Since New York Central Park is a hot spot for people all around the world it is pretty crowded and loading times are huge resulting in the "Populating Pokestops" message.
