### ISSUE TITLE
Pokebuddy uses greatballs and ultraballs?

### ISSUE THREAD

**Issue by Youtil** [finndev/PokeBuddy#1001]
Title

**Comment by ChiisanaKoneko** [comment]
@Youtil yes it was said in recent update it will use the other ones but not sure if it is

**Comment by avechuche** [comment]
Yes

**Comment by pixelpeeker** [comment]
i think is a yes, but it primarily uses the red ones.
btw everyones getting the "out of range" notification, better not to use the bot right now :)

**Comment by ChiisanaKoneko** [comment]
my bot works fine i get that error where there's no pokestops near by  till one of them refreshes then can walk again

**Comment by pixelpeeker** [comment]
@ChiisanaKoneko i dont know what exactly what happen. but i think niantic is sweeping bot users. i got that out of range notification 30 minutes ago where people got the same about 4 hours

**Comment by Youtil** [comment]
Thanks for the answers

**Comment by ChiisanaKoneko** [comment]
@pixelpeeker my bot is still running fine its been like 2 hours since i started it no problems
