### ISSUE TITLE
what is the point to use Quick Spin?

### ISSUE THREAD

**Issue by weilinzung** [finndev/PokeBuddy#1042]
I try to use it before I run the PokeBuddy. After I got baned, then I try to run the QuickSpin, it said failed to unban. So, the quick Spin only works if you are not unban, doesn't works after baned.

![screen shot 2016-08-13 at 8 19 48 am](https://cloud.githubusercontent.com/assets/7368063/17643156/0df8bbd4-612f-11e6-8b4b-adb9da2aa7a9.png)

**Comment by majdak79** [comment]
quickspin is obsolate. there is not more the option ton unbann after 40 spins

**Comment by AlexCtasy** [comment]
u got this error cause maybe in game ur problem is that u can see any pokestops, maybe the program quickspin dont see it too xD, btw when i was banned i tried quickspin, the program notificated that i was unbanned but btw not, SO quickspin is not working anymore.

**Comment by lightingtk** [comment]
if it doesn't work it mean that you're ip ban.

**Comment by AlexCtasy** [comment]
Quickspin not work, I used yesterday all works fine, show that u are sucessfull unbanned but the error was same, So u just need wait 1-12hs if you dont get unbanned maybe its a perma ban.
