### ISSUE TITLE
Any idea where this select 'other' crap is at? 

### ISSUE THREAD

**Issue by henryjames7714** [finndev/PokeBuddy#1077]
[P - 22:25:13] [Error] GoogleAuthError: NeedsBrowser
[P - 22:25:13] [Error] GoogleAuthError: You have two factor enabled.
[P - 22:25:13] [Info] Opening Google App-Passwords. Create a new password and select 'Other' as device.
[P - 22:25:13] [Info] Set the password in the settings once done!
[P - 22:25:14] Failed to login.

Changed my password but cant find the select other device part

**Comment by flixwito** [comment]
"You have two factor enabled." (2-step verification)
Nuff said. Just disable it.

**Comment by finndev** [comment]
https://security.google.com/settings/security/apppasswords

here
