### ISSUE TITLE
Virus threat on PokeBuddy.exe

### ISSUE THREAD

**Issue by Ojaa** [finndev/PokeBuddy#109]
Via NOD32:

01.08.2016 21:37:04	
D:\temp\7A8C.tmp	модифицированный MSIL/Packed.Confuser.J C:\Users\User\AppData\Local\Google\Chrome\Application\chrome.exe (3653C6A74560A5B8D61C18ADF239708F35842481).	63A33CFBDF16348E02F105F27D2C75DA0D1D5D59

01.08.2016 21:22:13
D:\temp\PokeBuddy-master\PokeBuddy-master\Loader\PokeBuddy.exe
модифицированный MSIL/Packed.Confuser.J
User-PC\User	Событие произошло в новом файле, созданном следующим приложением: D:\Program Files\WinRAR\WinRAR.exe (A46FE76CA7F297C281A5F7D6D7162DA23A6F7A9C).	63A33CFBDF16348E02F105F27D2C75DA0D1D5D59

**Comment by Vanethir** [comment]
Some antivirus programms might accuse PokeBuddy falsely to be a Virus.
Should be a problem with the Heuristic Engine of the Antivirus programm. Had same issue with Avira real time scanner blocking it for "HEUR/APC (Cloud)" reasons.

For more information check:
[Avira Heur/APC(Cloud)](https://www.avira.com/en/support-threats-summary/tid/7815/threat/HEUR.APC%20(Cloud))
[tomsguide user entry about Heurestic searching](http://www.tomsguide.com/answers/id-2774263/false-positive.html)

Run another antivirus test as well on [Virustotal](https://www.virustotal.com/en/url/f86ad6f87f4dcb57db9db228a8c4df2c057c4dd2e12f1f96d721eab61b9d45ca/analysis/1470077518/)

If you don't want to trust it anyways tryout [Sandboxie](http://sandboxie.com/). All in all to visit sites and try content you aren't 100% sure about.
