### ISSUE TITLE
PTC login failed

### ISSUE THREAD

**Issue by curtiola** [finndev/PokeBuddy#110]
When I try to log in with my PTC account, it keeps saying "[Error] The PTC servers are currently offline." but i can log in on my phone without any problems, this started about 4 hours ago, there were no problems beforehand.

**Comment by Vanethir** [comment]
Did you try to reinstall PokeBuddy? Sometimes even a computer restart works. Is it an account related problem? Might want to try a different account? Some people had problems with logging in on a specific account.

**Comment by curtiola** [comment]
I did try reinstalling pokebuddy, it's likely not an account problem since it's working on my phone and it was working on pokebuddy earlier, but I shall try making a new account and restarting my pc, thanks for the suggestions! I'll let you know how it goes.

**Comment by curtiola** [comment]
no luck with a different account or restarting my PC :(
maybe I got lucky signing in on my phone and the server is very unstable, I checked 2 PTC server status websites, one says it's down or very unstable and one says it's online, I will try again in an hour or so

**Comment by peterbeer990** [comment]
Same here guess its the servers playing up

**Comment by curtiola** [comment]
Yeah, the second site that once said servers are up now says they're unstable as well, sorry for the false issue Vanethir! It will resolve itself in time..
