### ISSUE TITLE
Lured Pokemons

### ISSUE THREAD

**Issue by andermateus** [finndev/PokeBuddy#1107]
Hey Guys,

I believe that my PokeBuddy caught only 'nearby' pokemons and doesn't see lured pokemons from PokeStops.  Can anyone confirm it?

Case it's true,  dev's can insert this update?

Thnx

**Comment by rmarquez5** [comment]
Actually my bot has caught lured pokes. However it won't stay at a lured Pokestop. So you will only catch one or two at that lure and move onto the next stop. You can stick to a spot if you set you walk speed to zero if you know it's being lured right now. But you have to manually set that and set the walk speed up again when you want to move on.

**Comment by andermateus** [comment]
Central park always is luring.
At the moment, i am using 6~8km/h.... I will try using 2km, inside central park.
thnx
