### ISSUE TITLE
Cant store some rare pokemons even if they've been marked favorite.

### ISSUE THREAD

**Issue by jesse8263** [finndev/PokeBuddy#111]
Even Dratini can't be stored cause it only stores the highest CP one among same pokemons now.
Plz change it back or separate those really rare pokemons from the bad ones.

**Comment by Vanethir** [comment]
[Duplicate to #98]

**Comment by LuzgGO** [comment]
I'd rather how it was, Vanethir please put it back from how it was 2 days ago

**Comment by Vanethir** [comment]
Finn is working on a solution right now. There will probably be a solution soon. Try to keep it in one issue post though for better overview, please.

**Comment by finndev** [comment]
You can configure what pokemons to transfer now.
