### ISSUE TITLE
ALL POKEMON TRANSFERED

### ISSUE THREAD

**Issue by massnigg** [finndev/PokeBuddy#1146]
I had 237 Pokemon and I left poke buddy running overnight to clear all my zubats, weedles and other stuff. When I came back this morning most of my Pokemon were GONE!!

PLZ HELP

**Comment by Rab89** [comment]
we cant help in any other way when the bot transfers pokemon its just like ingae you cannot revert it.
sorry to hear this but the bot or the devs cant do anything about it youve simply lost them.
