### ISSUE TITLE
All  pokestops out of range??!!

### ISSUE THREAD

**Issue by assasingbrother** [finndev/PokeBuddy#1161]
Please help.... restart and still like that....

**Comment by lilililo920** [comment]
stop, you will get banned sooner or later.

**Comment by assasingbrother** [comment]
sure?? ok....

**Comment by majdak79** [comment]
if you want to check out if your account is flagged, put a pokemon into an arene and click on the reward button in the shop. if you are good some hours later after a re-login, then you are safe.

**Comment by Demolition1986** [comment]
@majdak79 I did it, btw no make sense.

**Comment by DatHacksGaming** [comment]
@assasingbrother  please close your issue ticket as this has been discussed in GREAT length in other tickets that are still open...
