### ISSUE TITLE
Question about VPN

### ISSUE THREAD

**Issue by Aerial87** [finndev/PokeBuddy#1163]
I heard VPN must always be started if u wanna play more than 1 bot, but i'm not interested about that. If i just wanna play i still need VPN?

**Comment by Razdavitel** [comment]
If you just want to play then you don't need a VPN. the VPN is really only in case you get ip banned.

**Comment by DatHacksGaming** [comment]
@Aerial87 No you do not need VPN to play. VPN is simply to hide your IP as Razdavitel suggested. Unless you have further questions please mark this as closed. ^.^

**Comment by bradhibbert** [comment]
https://www.privatetunnel.com/home/?referral=J9ZH9ELB90

**Comment by Aerial87** [comment]
Thank you all!
