### ISSUE TITLE
Banned while playing manually with iPhone app

### ISSUE THREAD

**Issue by MariaBitterlich** [finndev/PokeBuddy#1165]
My bot accout was on level 25 and I was going to play manually using the normal app without botting from here on. Worked fine a whole day, but during car ride I got this perma ban.

Where can I try to appeal?

And do I get this banned account out of the app?

**Comment by N3HL** [comment]
[Here](https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal) you can appeal.

But consider your account done.

_"Please consider your account permanently terminated unless we reply back to your appeal."_

**Comment by MariaBitterlich** [comment]
Thanks, I know about the pretty minimal chance. But isn't it funny, that they ban exactly in that moment I play normal?

**Comment by N3HL** [comment]
Delayed bans are something companies have been using for years. It seems Niantic is no exception.

**Comment by MariaBitterlich** [comment]
@N3HL, I think the second ban wave hit me...

**Comment by matt2310** [comment]
@MariaBitterlich  whens the last time you got on and when were you banned?

**Comment by majdak79** [comment]
they can just ban you when you log in. so you play normal until.....

normally they ban in hour, after you cheated. it depends on, what you make in game. some things are triggering some not.

**Comment by majdak79** [comment]
their tos are very clear. i am just asking me, why people are stil cheating AFTER its known that they will be banned. i mean gps coordinates without latidute change? they have you after 15 minutes. its just matters what you make in game next. arenas? hahahaha

**Comment by matt2310** [comment]
I've been using blue stacks my account lvl 21, I hope it doesn't get banned... Worked fine when I logged in earlier in my phone with the GPS off

**Comment by MariaBitterlich** [comment]
@matt2310, I was playing for hours till 20 min before and got the ban exactly at that time.

**Comment by Demolition1986** [comment]
Well if u bot recently is a mistake, cause now is not a time to make any movements of bots. Cause they are banning as well.. If you bot in another country different than yours, so you get it banned. I used bot on my secondary account, of course farm here in my country no outside, using a cords of 13km of my home. And i got the second account with lv 25 I guess and still not banned yet.. So try to bot  in ur own country.

**Comment by barniebart** [comment]
is just a probem in the servers, accounts will be back soon
http://downdetector.com/status/pokemon-go

**Comment by matt2310** [comment]
That makes no sense if it were server problems none of my accounts should sign in....

**Comment by barniebart** [comment]
looks that its random some booters have this issue and some legal player are under the same circunstances.
I didnt try but i read that right now you cant even download the app from playstore

**Comment by Demolition1986** [comment]
Well i can download the real app from the apple store i fine with it.

And if "legal" players have same issue, maybe some players reported him to be investigated. And Niantic are banning all.

**Comment by barniebart** [comment]
Pokémon Go Servers
‏@PoGoServer

Many trainers are still experiencing log in issues with the error message "failed to get game data from server" Hang in there! #PokemonGO
What is the doubt?

**Comment by Demolition1986** [comment]
So u think all bot are not banned? well done.

**Comment by barniebart** [comment]
i think this all is a server problem mixed with mass hysteria, really

**Comment by lilililo920** [comment]
I do believe that niantic, sooner or later track down who use bot in their account and ban them, start from higher level.

Happy-Banned.

**Comment by Kokainium** [comment]
Hope to get my acc back:p if not fuck it :p the game annoyes me anyways :p

**Comment by DatHacksGaming** [comment]
You were banned for Botting, you likely leveled up too fast for when your account was created to now or simply botted in an obvious manner or during the bot detection. Please close your ticket as the community can't really do anything further other than link you to an appeal which will likely get denied from Niantic sadly, but that's the risk of cheating. We all know the risks going in.

@barniebart That twitter later mentions that it is a ban wave if you read their newer posts.

**Comment by Demolition1986** [comment]
Well i got perma banned my account that i used to teleports to anothers country to take rare pokemon, but my main that i never teleported just used spoof, still safe :)
