### ISSUE TITLE
Catching Pikachu at first human login?

### ISSUE THREAD

**Issue by MariaBitterlich** [finndev/PokeBuddy#1175]
I've started botting a completely fresh account (currently leel 17) and going to level it up to 25+ before manually login for real play the first time.

To check for IP ban I checked in yesterday without GPS and noted that the frist 3 initial pokemon are still araund me. When using this account the first time I want to catch pikachu with that widely spread behaviour. Has anybody tried that? Infact, what are the safest steps to initiate a purely botted account for the first time manually (pikachu, team choice, user name, ...)?

**Comment by karimavine** [comment]
I got 2 accounts lvl 22-23 botting i started by just login with my phone and choosing a starter pokemon and nickname 
then wait like an hour and open with bot  , you can choose the team later

**Comment by Rab89** [comment]
pretty sure thats an insta ban as the app has a timestamp of when you started playing, basically a lvl 25 account in less than a minute is definently gonna show up

**Comment by MariaBitterlich** [comment]
@Rab89, so what would be the best advice for a fresh account? First initiate all the settings and then start botting? And make breaks from botting due to real use every couple of levels?

Since I started my level 17 account abroad, I had to fill in a travel break to come back home from NYC.

**Comment by Rab89** [comment]
personally if i was to start botting again i would do the initiation first maybe wait a couple of hours and then bot, set limits and break  regularly say like 25- 50k.  or if you want to take a safer approach 10k and then have a break

**Comment by MariaBitterlich** [comment]
@Rab89, I agree, because this would be the most natrual setup:

1. Initiate manually with all the neccessary settings
2. Catch pikachu
3. Start botting in the same area
4. Breaks and switches to manual usage according to personal risk level
