### ISSUE TITLE
For some reason i dont Think this game Will live for long.

### ISSUE THREAD

**Issue by Kokainium** [finndev/PokeBuddy#1187]
This is not an issue just something i have been Thinking about :)
The reason why i dont Think this game Will die is that the pokemons is spread and if u dont live the right place u wont get shit out of it, becoz of that i Think like maybe 50 procent or more of the pokemon go player are/is (not sure which one to use:D) is using bot. The point of this game is to get em all and be the best, but its not possible if u dont live at the right location, and they want to make a fun and fair game, but i dont Think thats a fair game, correct  me of im wrong !

**Comment by Demolition1986** [comment]
@Kokainium I dont think like you, cause niantic will be put to you make a trades, so if u dont live in places that all the time have pokemon so u will be able to trade what u want.. Btw, games of niantic was made for spoof, you really think that spoff will be banneable? Of course not.. They have no way to check if u are using spoof, while you are using it in just way. Impossible to be detected!.. And i lot of players are using spoof just cause live in places that ofc don't have pokestops etc..

**Comment by Demolition1986** [comment]
And i agree to ppl use spoof, so to improve the game and have good players ++ to play with, spoof is the way of ppl that don't have poke close.

**Comment by Kokainium** [comment]
If thats true then they ban everyone who have been using bot, coz after i stopped botting u used spoof and got banned...

**Comment by Demolition1986** [comment]
@Kokainium I still using spoof, ill never stop to use it.. Btw my main account is not banned.. I just got banned on account of training. xD Cause i used teleport to catch rares pokemons.. Btw I think ill create another account lv 1 and ill start to lv up.. Better is have another extra account lv++ in these days.

**Comment by Kokainium** [comment]
But u Will get banned :) im sure

**Comment by Demolition1986** [comment]
@Kokainium Stfu, you're that noob who report hackers oxaoxoaox and hxoaoxoa dumbass.

I still safe and i bet you ill not get banned, just because im not noob and i know how to use it. :[)

**Comment by qyxii69** [comment]
my spoofed account is lvl 34... and it's not banned :) IF you stay 5-10km within your area. they won't be able to PICK IT UP. since your wifi connection is the same as the phones registry. :)

**Comment by Demolition1986** [comment]
@qyxii69 I dont get it about the wifi? In my house I use my own Wifi connection, and in my work I used work wifi connection, sometimes i use just 4G to play.. So is ok right? I dont get the point about wifi phones registry.. Btw here lv29 used of course with spoof and still using with spoof for IOS and not banned. xD farmining manually already.

**Comment by Brightblazer** [comment]
@Demolition1986  hey sorry for sending you same messaage but i forgot where i wrote you yesterday and cant see if you answered me cause the feed is has lot of new topic my gf bannjed too yesterday night   and as i told we anly you the fly gps she was 22 lvl and no gym battles or any pokemon assigned  in order someone have the chance to rpeort her , and ofc she didnt bot , i am considering if our accs are banned due to the fact we were apk players is there any chance they ban the player who had access from the apk? i mena the date the account was created was before the release in our country , although we download and play from the official version whne it was released what do oyou thinkl?

**Comment by JewBagel** [comment]
you will all be banned spoofing botting its all against the rules idk why this demolition guy thinks hes so special your account will be gone soon dont worry your just wasting time.... there is no smart way to go about cheating at this point you just haven't been under review yet but you will be

**Comment by Demolition1986** [comment]
@JewBagel Oh yes, maybe I was under investigation, i got a ban for 12h and now i playing fine.. Btw I dont care if I get ban for using spoof dude, if I get ban i relax.. Cause In my country I cannot go find pokemon in the street so, I know players that play with a spoof years and still not ban from games, if you think that spoof is baneable, tell me how Niantic can do it, is impossible.. Depends how u use it.. That's all.. Some players are smart and others get ban ;) All here is about how u use it. I still safe with my main account, u really think ill be ban in future xaoxaox? OFC not, cause the crazy things from Niantic is doing right now, after it no one will remember this date xaxoaoxa.. 

Think about this, i recently make an new account, used spoof to teleport, bots and i got banned so fast.. My account still safe, under investigation? xaoxoaox believe please.

@Brightblazer Well I dont know, something happened there with ur gf, she abussed some features of the spoof i sure about that, if she is in the same spot like 13khm of her house, using it as SAVED! places in the spoof, is no way to get banned, also, x1 or x2 of speed. And playing manual, is no way to get detected and banned. I do it and i still alive .

**Comment by Kokainium** [comment]
Are u stupid or something? 😑@demolition

**Comment by Demolition1986** [comment]
@Kokainium U was perma banned and u come to say anothers will be too, what a piece of dumb you're. Stop with kokain.

**Comment by Kokainium** [comment]
@Demolition... well just say ingen what the internet is saying... but u dont have to be rude 🤔

**Comment by Kokainium** [comment]
Saying *

**Comment by Kokainium** [comment]
And im not the only one saying it mr special guy....

**Comment by Demolition1986** [comment]
Special I have between my legs bro. :) I know you're mad bro of your account banned.

**Comment by Kokainium** [comment]
Actually im not :)

**Comment by Demolition1986** [comment]
Lets bots in necrobot and u will see that u gonna have an account +20 in 3hours without ban, ;[)

**Comment by Rab89** [comment]
necrobots far more superior in terms of features

**Comment by Demolition** [comment]
man, this isn`t my account

2016-08-17 10:04 GMT+03:00 Rab89 <notifications@github.com>:
