### ISSUE TITLE
Lucky Egg Pidgey/Caterpie/Rattata Stacking - how does Pokeboddy algo work?

### ISSUE THREAD

**Issue by MariaBitterlich** [finndev/PokeBuddy#1195]
Obviously the option "Use lucky egg while evolving if X > Pokemon available" indicates that Pokebuddy supports Pidgey/Caterpie/Rattata (PCR)-Stacking to maximize XP in those 30 min. of a lucky egg. But how dows the algo work?

You basically need an optimum of X PCR and 12*X PCR, prevously sent in. If I don't select "Transfer bad Pokemon" than there are not enough bonbon to evolve, but if I select this option, Pokebuddy sends ALL evolvable PCR in.

So I guess Pokebuddy does not make this times 12 optimization and to do it manually is kind of hard, because you don't see the PCR bonbon counter.

So, what is the best way for PCR stacking?

**Comment by Erlius** [comment]
i dont think its work right now. If you tick transfer bad pokemon, and you have 2 pidgey, the lower cp will be transfer. and to evolve using egg also not working.
