### ISSUE TITLE
My bot runs fine, but then i get this message...

### ISSUE THREAD

**Issue by AlexTheCreator** [finndev/PokeBuddy#1201]
I used the bot earlier today, i got a soft ban or two, but got back on track. Now when i'm using the bot i get these messages, whoch i haven't gotten all day, anyone who can help?

First image: http://imgur.com/aPqq6vw
Second image: http://imgur.com/FcPZlfF

**Comment by rmarquez5** [comment]
Wrong forum? You'll only find support here for pokebuddy not pikabot,
