### ISSUE TITLE
[Error] The PTC servers are currently offline

### ISSUE THREAD

**Issue by chrizfilmz** [finndev/PokeBuddy#122]
the bot tells me this everytime ive tried to log in today, the servers are not down (ispokemongodownornot.com) and i can log in fine on the app so i think its a bug in the newest version of the bot it worked fin until i updated

**Comment by curtiola** [comment]
pokemon go isn't down, you can sign in with google still, but pokemon trainer club is down
http://cmmcd.com/PokemonTrainerClub/

**Comment by chrizfilmz** [comment]
@curtiola its been like this the past few hours so i thought the servers was just down, but everytime i try to log in from the app on my phone i come directly in

**Comment by curtiola** [comment]
strange, im trying to sign in with PTC on my phone every few minutes just to check, with no luck, I'm in canada though so it's possible that it's region related

**Comment by Vanethir** [comment]
If I remember correctly someone else had and solved this problem today.
He simply changed his settings to google login (just checked the box), started the Bot for incorrect login and changed back to PTC login. 
Would you like to test it? :)

**Comment by chrizfilmz** [comment]
@Vanethir ill check now :)

**Comment by Mamutebr** [comment]
PTC this unstable
when it works
time does not work

**Comment by curtiola** [comment]
tested, still says PTC servers are offline for me

**Comment by chrizfilmz** [comment]
@Vanethir it did not work i still get the error then stopping

**Comment by Mamutebr** [comment]
See time [P - 19:53:54] Logging in with method: PTC as Auth Provider
[P - 19:54:16] [Error] The PTC servers are currently offline.

**Comment by curtiola** [comment]
I believe it's the PTC servers actually being down or very unstable, I could be wrong but I can't sign in on my phone either

**Comment by chrizfilmz** [comment]
i just tried again to test on the app and got directly in, weird

**Comment by curtiola** [comment]
It's possible Pokebuddy uses the Europe servers, which are down according to http://ispokemongodownornot.com/
I can't find any mention of Canada on any website, not sure if I would be piggybacking off the US server or not but either way its not working for me lol

**Comment by Vanethir** [comment]
Hmm I am clueless. I do not have any problems to login with any PTC Account. :/ Shouldn't be a PTC Location problem either. USA + Germany seem to work fine. 
One of them standing in Central Park New York, the other one in Hamburg Germany. Probably you should try to reinstall it?

**Comment by chrizfilmz** [comment]
i think the servers are fixed cause it works now :)
