### ISSUE TITLE
Unable to authenticate: banned

### ISSUE THREAD

**Issue by manuelcanizares** [finndev/PokeBuddy#1221]
Hi everybody! And thanks for the awesome work you do everyday! From yesterday I cannot login in pokemon go and "unable to authenticate" appears every time I try to enter. Does it mean I got banned? I have never received a soft ban so far. I don't abuse pokebuddy as I always wait the time I would need to come back home by car or by airplane.

**Comment by Demolition1986** [comment]
Try log out and log in a lot times, i got same error but u can log.. Keep trying, that is issue with logins.

**Comment by manuelcanizares** [comment]
My bad, another phrase appears, I am opening another thread and closing this one
