### ISSUE TITLE
bot not working properly....none of the pokestops or pokemon are loading.....just keeps updating pokestops

### ISSUE THREAD

**Issue by njk123** [finndev/PokeBuddy#1284]

**Comment by joyzie17** [comment]
you got soft ban dude who many hours did you play anyway?

**Comment by bloodygear21** [comment]
I think this is because the "no delay transfer".. it will work first then after a few minutes, this issue will happen.

**Comment by ST1998** [comment]
Well it happened to me, I do not know how to explain why.

**Comment by bloodygear21** [comment]
![image](https://cloud.githubusercontent.com/assets/21285721/18032511/c0015b40-6d39-11e6-8f84-76469418184c.png)

**Comment by bloodygear21** [comment]
I don't know if it is the bot or my net...

![image](https://cloud.githubusercontent.com/assets/21285721/18032578/8154a72e-6d3b-11e6-8adf-74338ab93467.png)

**Comment by njk123** [comment]
nevermind it was jst an ip ban
