### ISSUE TITLE
Doesn't catch Pokemon anymore, Transfer of whitelist Pokemon, Transfer of Pokemon without timeout

### ISSUE THREAD

**Issue by Blubb123** [finndev/PokeBuddy#1288]
Doesn't catch Pokemon anymore
Transfer of whitelist Pokemon
Transfer of Pokemon without timeout

**Comment by bloodygear21** [comment]
Again... does not catch @_@

here is the error...
[Pokebuddy_error.txt](https://github.com/finndev/PokeBuddy/files/441135/Pokebuddy_error.txt)

**Comment by hellspawngr** [comment]
same here. farms pokestops but doesn't catch pokemons even though it detects them.

**Comment by vicrya** [comment]
same here: doesnt catch anymore

**Comment by ch4chis** [comment]
same, doesnt catch pokemon

**Comment by njk123** [comment]
same here

**Comment by Blubb123** [comment]
issue fixed
