### ISSUE TITLE
EncounterNotFound Error

### ISSUE THREAD

**Issue by PDeception** [finndev/PokeBuddy#129]
Everytime I run into a pokemon to catch, it gives me the error

[Catch Pokemon] Encounter failed: EncounterNotFound (can't catch Pokemon)
I've tried restarting the application, but it still did not fix it. Also, I am not banned, I still recieve EXP from PokeStops.

> [P - 21:45:58] [Recycling Items] Recycled: ItemPokeBall x 3
[P - 21:45:59] [Recycling Items] Recycled: ItemGreatBall x 1
[P - 21:46:00] [UI] Updating...
[P - 21:46:00] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 21:46:01] [Recycling Items] Recycled: ItemPotion x 1
[P - 21:46:01] [Catch Pokemon] Encounter failed: EncounterNotFound (can't catch Pokemon)

**Comment by terminatrix1205** [comment]
same here im getting this too. thanks for taking a look

**Comment by PDeception** [comment]
Oh okay. Glad its not just me. Maybe its the Pokemon Go Servers in that case.

**Comment by finndev** [comment]
Hi, do you still experience this issue with the last version (restart)?

**Comment by PDeception** [comment]
This just now started, in the middle of using the program. How do I check my version? I believe it is the latest version.

**Comment by finndev** [comment]
Check the first log entry (copy whole log with CTRL+A, paste in notepad, check 2nd row)

**Comment by PDeception** [comment]
I am using Version: 0.0.6.1

**Comment by finndev** [comment]
Do you get this mulitiple times, or just once every while?

**Comment by PDeception** [comment]
Over and over, many times. It successfully catches a pokemon very rarely.

**Comment by terminatrix1205** [comment]
for me its half half. seems to be worse at certain area. once the bot moved away from there, it starts catching normally again. hope this helps.

**Comment by PDeception** [comment]
Oh okay, mine haven't really moved from the one area.

**Comment by terminatrix1205** [comment]
it pretty small here. when i said area i was talking about the area around certain pokestops. after moving about 100M from the bad one then it catches normally. anyway this thing just started few hours ago.

**Comment by YawYawz** [comment]
True, I'm here because of the same reason. EncounterNotFound

**Comment by terminatrix1205** [comment]
![poke](https://cloud.githubusercontent.com/assets/20784367/17315150/dba62090-589b-11e6-9c02-408f2f7229b0.JPG)
here you can see it fails frequently near the coastal area and
![poke2](https://cloud.githubusercontent.com/assets/20784367/17315184/20e90ef6-589c-11e6-982d-e467c4a992b6.JPG)
 it turns ok after moving away from it.

**Comment by PDeception** [comment]
I'm near no coastal area, but I am in Japan,

**Comment by terminatrix1205** [comment]
just to show the pattern of how it happens to me. it doesnt mean its specific to coastal area ;)

**Comment by ezudha** [comment]
Same the problem, i got it many times :(

**Comment by rmarquez5** [comment]
It's happening to me as well. Only started tonight though. Had it running for over 8 hours today and stopped it to do some video processing. Surprised that it stopped working and was worried I was banned. But as someone else mentioned above I'm still getting XP from Pokestops. My catch attempts result in that same error.

**Comment by ezudha** [comment]
How this?

**Comment by IAmYawz** [comment]
Any fix for this?

**Comment by dswtech** [comment]
I think its the pokemon server caused this,

I'm trying playing with Nox, and stayed on Lured Pokestops, some magicarp pop out at the same place, and same spot, but when I clicked, its dissapear from screen ...

**Comment by PDeception** [comment]
This problem was caused by the Pokemon Go Servers, and its fixed now.
