### ISSUE TITLE
[P - 12:49:43] [Farm Pokestops] Updating Pokestops...  [Farm Pokestops] Failed to update Pokestops. Trying again... 

### ISSUE THREAD

**Issue by xJockerBR** [finndev/PokeBuddy#1290]

**Comment by masamimiyu** [comment]
mine's working fine... Did you update your bot already?

**Comment by Blubb123** [comment]
mine working fine too

**Comment by xJockerBR** [comment]
Update (OK)
Run as adm(OK)
[Farm Pokestops] Updating Pokestops... [Farm Pokestops] Failed to update Pokestops. Trying again... (AGAIN )

**Comment by xJockerBR** [comment]
started working again \o/
