### ISSUE TITLE
 Populated  & Pokestops with data from EB API! no pokestops on the map

### ISSUE THREAD

**Issue by Ray-PoGo-NL** [finndev/PokeBuddy#1298]
[P - 23:05:11] Attempting to Login...
[P - 23:05:11] Logging in with method: Google as Auth Provider
[P - 23:05:14] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/187
[P - 23:05:14] [Farm Pokestops] Updating Pokestops...
[P - 23:05:16] [Farm Pokestops] Populated Pokestops with data from EB API!
[P - 23:05:16] [Navigation] Walking from: 52.26917, 6.79664 to: 52.28691, 6.80537 with a distance of: 1280 meters

**Comment by ST1998** [comment]
It is normal that happens. Or you have to wait or you have to transport yourself somewhere else.
