### ISSUE TITLE
IP adress?

### ISSUE THREAD

**Issue by MukyGamesNL** [finndev/PokeBuddy#1315]
[P - 13:54:56] [Farm Pokestops] Updating Pokestops...
[P - 13:54:56] [Farm Pokestops] Niantic did not send us any Pokestop, try to change your IP. Trying to continue anyways...
[P - 13:54:56] [Farm Pokestops] Populated Pokestops (PokeBuddy API)!
[P - 13:54:57] [Navigation] Walking from: 34.00894, -118.49738 to: 34.00889, -118.49732 with a distance of: 5 meters
[P - 13:54:57] [Farm Pokestops] Spinning Pokestop: 'Playland Arcade'
[P - 13:54:58] [Farm Pokestops] OutOfRange -> Pokestop Softban (try to change your IP)

what do i need to do to solve this?

**Comment by ST1998** [comment]
You must stop the program and wait for at least 1-4 hours.

**Comment by Ray-PoGo-NL** [comment]
@MukyGamesNL
if it is good update pokebuddy Populated Pokestops (PokeBuddy APP)!


https://www.youtube.com/channel/UCzbnqXgPKQdtjjxqvQ2WFXg
 


[P - 19:44:04] Attempting to Login...
[P - 19:44:04] Logging in with method: Google as Auth Provider
[P - 19:44:11] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/50
[P - 19:44:13] [Farm Pokestops] Updating Pokestops...
[P - 19:44:13] [Farm Pokestops] Niantic did not send us any Pokestop, try to change your IP. Trying to continue anyways...
[P - 19:44:16] [Farm Pokestops] Populated Pokestops (PokeBuddy API)!
[P - 19:44:18] [Navigation] Walking from: 25.75997, -80.25228 to: 25.76225, -80.23896 with a distance of: 843 meters
[P - 19:44:21] [OnLevelUpEvent] Level up to: 28, congrats!
[P - 19:46:27] [Farm Pokestops] Spinning Pokestop: 'Rampway Fishing Mural'
[P - 19:46:28] [Farm Pokestops] Success -> Received XP: 50
[P - 19:46:43] [Navigation] Walking from: 25.76224, -80.23902 to: 25.7632, -80.23866 with a distance of: 70 meters
[P - 19:46:54] [Farm Pokestops] Spinning Pokestop: 'Iglesia Episcopal De Todos Los Santos'
[P - 19:46:54] [Farm Pokestops] Success -> Received XP: 50
[P - 19:47:08] [Catch Pokemon] Found: 2 catchable Pokemon
[P - 19:47:10] [Catch Pokemon] Using a Berry to catch Pokemon!
[P - 19:47:11] [Catch Pokemon] Berry has been successfully used
[P - 19:47:11] [Catch Pokemon] We caught a Pidgey (Probability: 28.81%) with CP 421, used 1 x ItemPokeBall and received 160 XP

**Comment by MukyGamesNL** [comment]
thanks guys, my bot is working fine now

bedankt ;) de bot werkt weer gewoon zoals t werkt nadat ik m ff paar uurtjes had uitgelaten haha

**Comment by Ray-PoGo-NL** [comment]
@MukyGamesNL 

heb jij nu ook probelem met in loggen  van pokebuddy
do you now probelem  logging pokebuddy
