### ISSUE TITLE
how to transfering magikarp?

### ISSUE THREAD

**Issue by ezudha** [finndev/PokeBuddy#138]
I have many magikarp, n its not transfer. What should i do?

**Comment by IamDeric** [comment]
same here. it doesn't transfer at first time. try doing this. will the bot is running. try to check and uncheck the magickarp box, and click done. see if something happen, i just did it now and it transfer some of my magickarp.

**Comment by ezudha** [comment]
I did it n doesnt work

**Comment by IamDeric** [comment]
i think we need to wait for the new update. you can do it manually.

**Comment by Vanethir** [comment]
Hotfix for transfering Margikarps is out. Transfer List for Pokemon still bugged. :)

**Comment by IamDeric** [comment]
Magickarp transfer is working fine with me. With the new update.
