### ISSUE TITLE
Not transferring Eevees

### ISSUE THREAD

**Issue by 404unknown** [finndev/PokeBuddy#140]
Pokebuddy is not transferring any Eevees, same goes for its elder brothers Vaporeon, Jolteon and Flareon. I now got like 10+ of each pokemons in my 5 accounts. It is quite annoying as I need to manual transfer them on all my 5 accounts. The "Do not transfer" box for Eevees wasnt checked and Im running the latest version (0.6.1) if that helps.  Is it happening to others or is it just me?

**Comment by Vanethir** [comment]
Transer bad Pokemon option is  unfortunately still bugged.

**Comment by 404unknown** [comment]
Ok thanks
