### ISSUE TITLE
bad magikarp does not transfer automatically fix please

### ISSUE THREAD

**Issue by BlackSkulll** [finndev/PokeBuddy#147]
have 100 Magikarp PokemonInventoryFull
[P - 07:54:41] [Catch Pokemon] Encounter failed: PokemonInventoryFull (can't catch Pokemon)
[P - 07:54:45] [Transferring Pokemons] No Pokemons available for transfer. Trying again later..

**Comment by Vanethir** [comment]
Try to transfer them manually. Pokemon transfer option still bugged.

**Comment by Mamutebr** [comment]
bad Eevee too :p

**Comment by wolfwood69** [comment]
it tranfer my pinsir cp 1380 and cp 1230 too, even though it already on "do not tranfer selected" checklist, and now only one pinsir cp 1440 left....

**Comment by therealpequod** [comment]
also dratini, got 7 of 'em. Nice job anyway ;)
