### ISSUE TITLE
Berry Percentage limiter not working

### ISSUE THREAD

**Issue by greagan01** [finndev/PokeBuddy#154]
Razzberries are used to aid capture regardless of the percentage entered to limit the use. Berries seem to have a default use when capture percentage is less than 35% and any user value for the percentage is ignored.

On the whole the most recent updates are awesome. I haven't been having any real issues with the transfer or evolve. Code to use Ultra Balls and Great Balls when capture percentage is less than certain amounts, and CP is greater than certain amounts, or when pokemon is 'uncommon' or 'rare' type would be awesome.

**Comment by greagan01** [comment]
On further testing, the checkbox to use Berry is ignored too. The bot always uses berries whether it is checked or not. The percentage may work if the checkbox had an effect.

**Comment by Vanethir** [comment]
Already mentioned in #55 . Not working/fixed yet. :)

**Comment by finndev** [comment]
Fixed in 0.0.6.3, thanks for reporting mate
