### ISSUE TITLE
Bug: Evolvable Pokemons

### ISSUE THREAD

**Issue by k2sapex** [finndev/PokeBuddy#157]
I have a lot of pokemons for evolve but in the window of evolvable pokemons i dont see anyone would be good if u guys fix it, thanks!

**Comment by Vanethir** [comment]
The evolvable Pokemon window only shows Pokemon marked as "Evolve selected" within your 'Settings'->'Pokemon Settings'.

**Comment by k2sapex** [comment]
Ahhhh okey thats new thanks for response
