### ISSUE TITLE
Receiving 0 Exp

### ISSUE THREAD

**Issue by Tolyox** [finndev/PokeBuddy#16]
Not getting any exp for spinning pokestops and every pokemon flees

**Comment by Bayramklc** [comment]
soft ban bro quick spin or pokestop 50 sping unbanned

**Comment by Tolyox** [comment]
Damn, alright thanks man, not sure what you meant by "quick spin or pokestop 50 sping ubanned"

**Comment by Bayramklc** [comment]
https://www.nulled.to/topic/175449-automatically-bypass-pokemon-go-soft-bans/page-1

used

**Comment by Vanethir** [comment]
If you don't want to waste any Pokeballs: Turn the option for catching Pokemon off. 
Press start and wait until you get XP (shouldn't take more than 5 minutes). Turn catching Pokemon on again afterwards and everything should work fine.

You can get a soft ban if you travel more than 10 km at once.

**Comment by Tolyox** [comment]
Gotcha, sorry for the stupid questions and thanks for the answers!
