### ISSUE TITLE
PokeBuddy does not get my items, pokemons, level etc. statistics

### ISSUE THREAD

**Issue by fedkassad7** [finndev/PokeBuddy#160]
For some reason after the last update PokeBuddy does not show information about my level, pokemons etc. As a result of this it cannot transfer my bad pokemons and the inventory fills up very quickly. If I manually transfer pokemons it can still catch and farm pokestops but transfering still does not work.

I thought about deleting the client and installing a fresh one.

**Comment by inkompetent** [comment]
Could you send me your log?

**Comment by lordofthereef** [comment]
This happened to me once too. I had to reboot my PC.

**Comment by fedkassad7** [comment]
Rebooting solved the issues. Thanks.
