### ISSUE TITLE
Catcherror on all pokemon, Pokestops give 0xp

### ISSUE THREAD

**Issue by Pspada117** [finndev/PokeBuddy#166]
Hello! 

Awesome program btw! Everything was working good this morning at 8:30est, I closed and reopened the program at lunch time and every pokemon that is found receives a CATCHERROR in yellow, and every pokestop gives me 0xp. 

Any ideas? 

Thanks Again!

**Comment by Vanethir** [comment]
Try to increase number of Pokeballs you keep. There is a problem with Greatball/Ultraball usage right now.

**Comment by LuzgGO** [comment]
You took a soft ban because you made teleport, just wait many hours

**Comment by Pspada117** [comment]
Thank you very much for the help! I removed the soft ban by going to a pokestop. I spun the disk and closed the pokestop, and did this roughly 50 times until I was able to collect items from it. This eventually removed the soft ban and I was able to get back on in 15 minutes.

**Comment by inkompetent** [comment]
@Pspada117 
You only need to run Pokebuddy - after ~ 5 Minutes the ban will autoremove because the program try to spin pokestops ;)
