### ISSUE TITLE
NoResultSet | FULL CRASH

### ISSUE THREAD

**Issue by inkompetent** [finndev/PokeBuddy#178]
[P - 00:33:51] [Catch Pokemon] Encounter failed: Unknown (can't catch Pokemon)
[P - 00:33:51] [UI] Updating...
[P - 00:33:52] [Navigation] Walking from: 46.2479, 20.14704 to: 46.24782, 20.14715 with a distance of: 8 meters
[P - 00:33:52] [UI] Updating...
[P - 00:33:53] [Farm Pokestops] Spinning Pokestop: 'II. Rákóczi Ferenc Szobra'
[P - 00:33:53] [Farm Pokestops] NoResultSet -> Received XP: 0
[P - 00:33:55] [Catch Pokemon] No Pokemon nearby. Retrying in 80meters
[P - 00:33:57] [Catch Pokemon] Encounter failed: Unknown (can't catch Pokemon)
[P - 00:33:57] [Catch Pokemon] No Pokemon nearby. Retrying in 80meters
[P - 00:33:57] [Navigation] Walking from: 46.24782, 20.14715 to: 46.24781, 20.14659 with a distance of: 27 meters
[P - 00:33:57] [UI] Updating...
[P - 00:33:58] [UI] Updating...
[P - 00:33:59] [Catch Pokemon] Encounter failed: Unknown (can't catch Pokemon)
[P - 00:33:59] [Navigation] Walking from: 46.24782, 20.14693 to: 46.24781, 20.14659 with a distance of: 16 meters
[P - 00:34:00] [Farm Pokestops] Spinning Pokestop: ''
[P - 00:34:00] [Farm Pokestops] NoResultSet -> Received XP: 0
[P - 00:34:00] [Farm Pokestops] Spinning Pokestop: ''
[P - 00:34:01] [Farm Pokestops] NoResultSet -> Received XP: 0
[P - 00:34:04] [UI] Updating...
[P - 00:34:04] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 00:34:04] [Catch Pokemon] Encounter failed: EncounterError (can't catch Pokemon)
[P - 00:34:05] [UI] Updating...
[P - 00:34:05] [Catch Pokemon] No Pokemon nearby. Retrying in 80meters
[P - 00:34:07] [Navigation] Walking from: 46.24781, 20.14661 to: 46.24779, 20.14585 with a distance of: 36 meters
[P - 00:34:09] [UI] Updating...
[P - 00:34:09] [Farm Pokestops] Spinning Pokestop: ''
[P - 00:34:09] [Farm Pokestops] NoResultSet -> Received XP: 0
[P - 00:34:09] [Navigation] Walking from: 46.2478, 20.14603 to: 46.24779, 20.14585 with a distance of: 8 meters
[P - 00:34:10] [UI] Updating...
[P - 00:34:10] [Farm Pokestops] Spinning Pokestop: 'Man and Lady Ornament '
[P - 00:34:11] [Farm Pokestops] NoResultSet -> Received XP: 0

**Comment by MikeTheory** [comment]
Getting the same thing as well

**Comment by inkompetent** [comment]
I think it was a API mistake.
It's now working.

**Comment by MikeTheory** [comment]
Same for me haha
