### ISSUE TITLE
Not getting EXP from poke stops , and all pokemon failing to be caught

### ISSUE THREAD

**Issue by Erfalis** [finndev/PokeBuddy#181]
It was working fine all day until i stopped it to check the game on my phone. After this the game just starting failing to catch pokemon and the poke stops dont give the 50 Exp anymore.

**Comment by Bi0tin** [comment]
If you have "position" (gps) enabled on your phone Pokemon GO will teleport to that area. So you probably got a soft ban that will last a couple of hours.

**Comment by MikeTheory** [comment]
Try rebooting your pc. I was having the same issue as was someone else and it fixed itself

**Comment by PDeception** [comment]
You're softbanned. Use QuickSpin, the program to unban yourself.

**Comment by Amnot** [comment]
@PDeception Thanks for the QuickSpin i fixed the problem with it!

**Comment by PDeception** [comment]
@Amnot No problem! Remember to close the thread!
