### ISSUE TITLE
hiya pokebuddy is using a berry on every pokemon and its set to 30% anyway of fixing this please

### ISSUE THREAD

**Issue by Smiffy2k5** [finndev/PokeBuddy#184]

**Comment by PDeception** [comment]
Make sure its set to 0.30 percent and not just 30?

**Comment by Smiffy2k5** [comment]
ill give it a go thankyou, also 3 days of using this and i've collected no lucky eggs or incubators is this a game issue?

**Comment by PDeception** [comment]
That depends on your level, but you can check the item limits you have set. Make sure the incubator option is set to a number. I haven't collected any lucky eggs, but I do get incubators. So that is not the bots issue.

**Comment by curtiola** [comment]
ive collected both lucky eggs and incubators as well, although even when i set the berry usage to 0.20 it still uses them on everything under a 40% chance for some reason

**Comment by Vanethir** [comment]
Hmm it's working for me :/

![Berries](http://i.imgur.com/30qHgvm.jpg)

**Comment by curtiola** [comment]
me too now, just had to restart pokebuddy xD
