### ISSUE TITLE
CatchError

### ISSUE THREAD

**Issue by apollon1954** [finndev/PokeBuddy#196]
Cannot catch pokemon still exists

**Comment by pokemonbotacc** [comment]
same here

**Comment by killer2318** [comment]
It is a bug, do you guys only have greatball and ultraball?
If you don't have pokeball this message will appear as the system will not use  greatball and ultraball

**Comment by apollon1954** [comment]
well i had 20 pokeballs maybe they ran out i have to check

**Comment by apollon1954** [comment]
nope i still have 24 pokeballs

**Comment by pokemonbotacc** [comment]
yea i cleared my inventory and its working again with the regular pokeballs

**Comment by denimdoon** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20809388/17357617/5bb0a4e2-597b-11e6-8987-cbb491ac341a.png)
how to solve this ?

**Comment by apollon1954** [comment]
problem solved.clear my bag,it worked
