### ISSUE TITLE
Bot stops after 30 minutes

### ISSUE THREAD

**Issue by Gurgamesh** [finndev/PokeBuddy#199]
Bot stops after each 30 minutes of run time, i have to start and stop it once again is it normal or not ?

**Comment by k2sapex** [comment]
No he didnt, try to download the lastest version of Pokebuddy, and will work, in the lastest its added forced to restart at 30mins, have a good day!

**Comment by Gurgamesh** [comment]
okey, thank you ^^

**Comment by Vanethir** [comment]
[Download Zip](https://github.com/finndev/PokeBuddy/archive/master.zip) option in *Clone or Download* menu on the Codepage.

**Comment by Gurgamesh** [comment]
it still stops after 30 minutes, please tell me what steps should i do to get it work fine,

**Comment by Vanethir** [comment]
[Original to #205]
Will close this to keep it in one issue report.
