### ISSUE TITLE
Stuck @ [UI] Updating ...

### ISSUE THREAD

**Issue by Rinkaku** [finndev/PokeBuddy#21]
Hello Guys,

the bot stuck @ [UI] Updating ... after about 30 min. 
Some help would be nice.

Greetings
Florian

**Comment by Vanethir** [comment]
Did you try to turn it off and on again? :)
Usually it takes 1-10 seconds for the update.

**Comment by Rinkaku** [comment]
Yeah after off and on it works again ...
But look at my attachment.
![2016-07-29 22_49_35-](https://cloud.githubusercontent.com/assets/20731130/17263119/7e2b25c8-55df-11e6-9e94-605105906b99.png)

**Comment by Paladz** [comment]
Same issue happen to me. I guess it's because google auth token expired
