### ISSUE TITLE
Walk Speed Question

### ISSUE THREAD

**Issue by UknownAX** [finndev/PokeBuddy#212]
What is the recommended walk speed? I dont wanna get banned and I'm using 40km as speed but if I can go faster withouth any problem I would like to know it.

**Comment by clarkeybear** [comment]
I tend to stay at 24 km/h, for me it has been the highest walk speed while also incubating eggs and it looks low-key.

**Comment by rmarquez5** [comment]
Really?!?! My bots go 10 km/hr. Never knew I could make it go that fast and still count the distance towards egg hatching. Thought the cap was around 20 (read that somewhere when the game first came out).

**Comment by PDeception** [comment]
I do 25, that way I'm guaranteed no ban.

**Comment by cswxin** [comment]
I'm using 40km also and teleporting

**Comment by Ander0128** [comment]
According to various sites it appears that 19km is the max safe bet to ensure you get distance on eggs. I know that I have gotten distance with higher speeds however.

**Comment by andreimanu** [comment]
I'm going with 15 and out of 20 km I only get around 3 on my eggs, so there's that.
