### ISSUE TITLE
Error NoSetResult and failed encounter

### ISSUE THREAD

**Issue by Fatality10** [finndev/PokeBuddy#214]
From some minutes is appearing an error in yellow that says: encounter failed can't catch pokemon" and appears also when farming a pokestop something like "NoSetResult 0xp received".

Someone knows what are those errors?

**Comment by rmarquez5** [comment]
For the pokemon catch error, do you have any red pokeballs left? You have to make sure you have at least some red pokeballs are in your inventory to better ensure that you will catch the target pokemon.

Farming stops with 0 XP may indicate a soft ban on your account. If you jumped too far from the last coordinates your character had, it will trigger an auto-soft ban on us. Give it 10-30 minutes and maybe it will clear up.

**Comment by Fatality10** [comment]
i wasn't banned, sometime it gives me the 50xp points, sometimes appear that error that gives 0

**Comment by rmarquez5** [comment]
Could be a server error on the Pokemon Go side, not on the bot. Hopefully it clears up.

**Comment by Vanethir** [comment]
Anything else besides **encounter failed can't catch pokemon** within the message? Usually it says something like **Pokemon inventory full** etc.
I think **NoSetResult** shouldn't effect your overall speed. You could try to restart your application. :)

**Comment by Fatality10** [comment]
Rebooted my pc, now it works. I had to make some changes in the item menu, to balance it.
My pokemon inventory wasn't full, i always have my phone with pokemon go actived to monitor how much pokemon i have and transfer the ones that the bot doesn't transfer. 
And besides, i'ts a bit annoying to lose some pokemons because i can't change the tipe of ball to use, something like that under the 50% capture rate it uses the great ball, and under the 30% it uses the ultra ball.

**Comment by Vanethir** [comment]
We are aware of that problem. :) Once fixed you should at least be able to get rid of all normal Pokeballs to use Greatballs instead. % based usage of different Pokeball types might be added as well in a future update. :)
