### ISSUE TITLE
Nothing shows up after Logging in with Google Auth Provider

### ISSUE THREAD

**Issue by Parthsp007** [finndev/PokeBuddy#219]
[P - 16:02:45] Feel free to donate to (PayPal): support@epicdevs.de (make sure to email me afterwards)
[P - 16:02:45] --------------------------------
[P - 16:02:53] Attempting to Login...
[P - 16:02:53] Logging in with method: Google as Auth Provider

It doesn't go further than that I tried closing it and reopening it but it still shows up. Please help.

**Comment by PDeception** [comment]
Ninantic just updated, the bot wont work until its updated too. Close the thread please.

**Comment by Vanethir** [comment]
Problem with Niantic servers mentioned in #218. Feel free to discuss there. :)
