### ISSUE TITLE
annoying prob

### ISSUE THREAD

**Issue by oOBlueArrowOo** [finndev/PokeBuddy#222]
it doesn't work I've redownloaded everything

**Comment by PDeception** [comment]
What doesnt work? Whats your problem?

**Comment by curtiola** [comment]
the way i understand it, they've changed the API and we must wait for the devs to update PokeBuddy, see #218

**Comment by Thrallix** [comment]
The issue you're facing is due to the Pokemon GO servers having issues once again.
Please refer to #218

**Comment by LuzgGO** [comment]
POKEMON GO aren't having servers problems, they updated, the game is now working on Brasil where I live

**Comment by liftur** [comment]
Yea, pokemon servers have been up, and many other applications have stopped working,

**Comment by itsmyoj** [comment]
when is it going to be updated?
