### ISSUE TITLE
Post good coordinates

### ISSUE THREAD

**Issue by PDeception** [finndev/PokeBuddy#224]
Post your favorite locations with their coordinates down below.

**_New York, Central Park_**
Lat: 40.771133 
Long: -73.974187

**_Santa Monica Pier_**
Lat: 34.009606
Long: -118.496812

**_San Francisco_**
Lat: 37.7510669
Long: -122.49731910000003

**Comment by Vanethir** [comment]
Check #197 to keep it in one Thread. :)
