### ISSUE TITLE
Bot is currently "Offline" due to broken API

### ISSUE THREAD

**Issue by hemipatu** [finndev/PokeBuddy#226]
So as most people are now aware, the bot is **not working** how it is supposed to; left with only the ability to transfer and evolve pokemon! 

From what I can find, it's simply down to the recent update that **Niantic** have pushed, causing the API used outdated/broken and If this project uses _tejado's_ pokemon go api, or something sourced from it's code... Just take a look;- [https://github.com/tejado/pgoapi/issues/176](url)

**Comment by Vanethir** [comment]
You are right. Check #218 :smiley:

**Comment by hemipatu** [comment]
Thank you @Vanethir didn't see that _ticket number_ on a damn mobile at the moment! Do you know if the API used is indeed the one that _tejado_ used at all?

**Comment by Vanethir** [comment]
Don't think it's in anyway related to it.
Finndev just estimated how long it will take in the other post though.

**Comment by smp163** [comment]
hey guys I was wonder could you guys make a dropbox so we can just download it off there. when your done updating the bot please. thanks
