### ISSUE TITLE
This is all its been saying

### ISSUE THREAD

**Issue by macajuki** [finndev/PokeBuddy#228]
[P - 16:40:15] [UI] Updating...
[P - 16:40:36] [UI] Updating...
[P - 16:40:57] [UI] Updating...
[P - 16:41:18] [UI] Updating...
[P - 16:41:39] [UI] Updating...
[P - 16:42:01] [UI] Updating...
[P - 16:42:22] [UI] Updating...
[P - 16:42:44] [UI] Updating...
[P - 16:43:07] [UI] Updating...
[P - 16:43:28] [UI] Updating...
[P - 16:43:49] [UI] Updating...
[P - 16:44:10] [UI] Updating...
[P - 16:44:31] [UI] Updating...
[P - 16:44:52] [UI] Updating...
[P - 16:45:13] [UI] Updating...
[P - 16:45:34] [UI] Updating...
[P - 16:45:56] [UI] Updating...

**Comment by Vanethir** [comment]
Same problem as mentioned in #218. :)

**Comment by macajuki** [comment]
Okay my bad sorry :)
