### ISSUE TITLE
Pokestop failure?

### ISSUE THREAD

**Issue by stas5678** [finndev/PokeBuddy#229]
I set the gps to an area with many known pokestops, but when I start the app it does not attempt to spin any of them. I am confused and not quite sure of what is going on, but if anyone else has encountered this I would be grateful to learn from their knowledge.
EDIT: tried again with a different account and got the same result, so its not a ban or anything...

**Comment by NuSynz** [comment]
The DEV team is aware of this issue. Pokemon GO updated the API so the dev is working on an update to get the bot back up and running. I'm experiencing the same thing.

**Comment by Vanethir** [comment]
#218 for more information. :)

**Comment by Cwoodytoday** [comment]
I cannot even log into my account.
