### ISSUE TITLE
Retrying request 

### ISSUE THREAD

**Issue by Xalk444** [finndev/PokeBuddy#23]
![default](https://cloud.githubusercontent.com/assets/20630520/17265465/e0c745aa-55f7-11e6-9fa4-2e0b91e6b232.jpg)
How to fix?

**Comment by Bayramklc** [comment]
Restart ?

**Comment by Xalk444** [comment]
I restarted 5-6 times
started to work in 30 minutes

**Comment by brijei** [comment]
this happens when the pogo servers are down.
