### ISSUE TITLE
bot is not working

### ISSUE THREAD

**Issue by gianlu696** [finndev/PokeBuddy#232]
the bot is not working at the moment, can we have more information about this situation?

**Comment by stas5678** [comment]
the developers stated that the bot would be up by an ESTIMATED time of 7:30 CEST, other than that we know that niantic updated the API for go, which is what is causing the problem with the bot. Beyond this, most threads are being cleaned up, please view the general discussion (#227) for more information as this is the main thread for this issue. It should be fine, and nothing to do but be nice and be patient.

**Comment by Vanethir** [comment]
Just a small correction: #227 ist for General discussion and offtopic content. 
Check #218 for reasons, updates, ETA :)
