### ISSUE TITLE
DONT WORK!

### ISSUE THREAD

**Issue by zerogamerg** [finndev/PokeBuddy#233]
[P - 21:15:54] Attempting to Login...
[P - 21:15:54] Logging in with method: Google as Auth Provider
[P - 21:15:57] Using RPC Endpoint: pgorelease.nianticlabs.com/plfe/302
[P - 21:15:57] [Catch Pokemon] No Pokemon nearby
[P - 21:16:02] [UI] Updating...
[P - 21:16:24] [UI] Updating...
[P - 21:16:46] [UI] Updating...

why dont work anymore?

**Comment by stas5678** [comment]
see thread #227, there was an update for the game api so the bot needs to have its api updated

**Comment by Vanethir** [comment]
Check #218 for information, status updates, ETA => general problem after niantic update :)

**Comment by HckrWest** [comment]
Is the bot officially down?

**Comment by finndev** [comment]
The bot is up and working.
