### ISSUE TITLE
Pokestops aren't loading, bots not moving

### ISSUE THREAD

**Issue by pokemonbotacc** [finndev/PokeBuddy#235]
Anyone experiencing problems with the Pokestops not loading in the map, also my bot isn't moving probably because pokestops aren't populated.  Its able to transfer, and evolve though.

**Comment by rmarquez5** [comment]
Thread 218 explains that the bot isn't working and is being fixed as we speak. We have to wait on them to release a new version. ETA was going to be in the 4-6 hours. Just check back later.
