### ISSUE TITLE
Laptop Resolution

### ISSUE THREAD

**Issue by TakRiuto** [finndev/PokeBuddy#236]
Hi, im from Venezuela!

I was wondering if there is way to adapt the size of Bot small resolutions (1024x600) because in my laptop the window does not open full, is cut ... Excuse my bad English, use a translator

**Comment by oOBlueArrowOo** [comment]
get a better res jk

**Comment by oOBlueArrowOo** [comment]
The devs are working on so many things at the moment though

**Comment by TakRiuto** [comment]
Yes, i know, is just a cuestion ^^

**Comment by Vanethir** [comment]
Low resolution might be something to be fixed within future updates. Right now it's unfortunately not possible to resize it.

**Comment by TakRiuto** [comment]
Thanks a lot ^^
