### ISSUE TITLE
Keep saying [UI] updating

### ISSUE THREAD

**Issue by shenn4** [finndev/PokeBuddy#237]
HI guys,
I downloaded pokebuddy and it  just worked few hours. After that, it keeps saying "[UI] updating ", it stopped farm pokestops and catch pokemon.  Transfer bad pokemon looks fine now.
Any one can help me to fix this or give me some suggestion?

**Comment by Vanethir** [comment]
Check #218 for updates. :)

**Comment by shenn4** [comment]
so what we can do now is just waiting for the bot updates API? And after that, the bot should works? @Vanethir

**Comment by Vanethir** [comment]
Yes. Just wait for the next update to fix it and you should be able to run PokeBuddy again. :)
