### ISSUE TITLE
Can i start it on Mac?

### ISSUE THREAD

**Issue by TommyFerra** [finndev/PokeBuddy#244]
Hi, someone had found a method to launch pokebuddy on Mac?

**Comment by jakerossi24** [comment]
Install Virtual Box using Windows is what I did or you can use Wine

**Comment by xiaojianan** [comment]
On Mac i recommend you PokemonGoBot, I use this on Windows and use PokemonGoBot on Mac.

**Comment by TommyFerra** [comment]
thx
