### ISSUE TITLE
just say No Pokemons available for transfer. Trying again later... There are no items to recycle

### ISSUE THREAD

**Issue by viktrok** [finndev/PokeBuddy#249]
only show this 
[P - 02:44:30] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 02:44:31] [Recycling Items] There are no items to recycle
[P - 02:44:36] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 02:44:37] [Recycling Items] There are no items to recycle
[P - 02:44:43] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 02:44:43] [Recycling Items] There are no items to recycle
[P - 02:46:42] [Catch Pokemon] No Pokemon nearby
[P - 02:46:45] [UI] Updating...
[P - 02:46:48] [UI] Updating...

how can i fix them thanks
 is ban?

**Comment by tlsuzu** [comment]
#218 
Waiting is the only thing we can do

**Comment by viktrok** [comment]
I've been waiting for a 8 hours :(

**Comment by fruor** [comment]
viktrok why don't you write some Blues Music in the meantime, complaining is more helpful there. 
I hope that the API haven't been made inaccessible by Niantic, either way I'm sure devs will try their best. So yes, waiting and composing music is the way to go.
