### ISSUE TITLE
Pokebuddy still not working

### ISSUE THREAD

**Issue by Myxa80** [finndev/PokeBuddy#250]
no stops nearby
no moving
only transferring pokemons

**Comment by viktrok** [comment]
#228 Api it's broke bro only we can to wait

**Comment by Myxa80** [comment]
thx for comment. kk.

**Comment by AntiquaBellator** [comment]
How are you guys getting on with the issue? Downloaded the app just after Niantic decided to change things. Was looking forward to trying out your bot. Hope all is going well and it'll be back up soon! 

Hope to hear about updates soon, peace.

**Comment by Vanethir** [comment]
Right now it's mostly waiting for the unknown6 to be decrypted. 
They are working with many developers on decrypting an unknown RPC so the messages sent to the server can be modified. Some of them being up for 20+ hours.

At the moment you can get new updates [here](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/) and honor their hard work. :heart: 

The first comment is posting a lot more detailed stuff.

**Comment by AntiquaBellator** [comment]
Thanks very much for your reply. Much appreciated! I've been following the
updates all day, sounds like some real progress has been made.

Hopefully things will be up and running in the next few days. Can't wait to
finally try out the bot.

Peace.

**Comment by johnkingsize** [comment]
WORKS FOR ME NOW!!! I click START in the program and next go to SETTINGS don´t do anything and next close the settings and click STOP !!!!! works for me

**Comment by Pimdegraaf** [comment]
The bot worked indeed but after 5-10 the pokestops disapeared and my bot started walking parts of 16 meters in random directions while doing nothing.

**Comment by EisHulk** [comment]
So I am having issues with the program running. The bot works for a short period and then stops completely. It also varies, sometimes it wont even load up the stops and never shows any pokemon. Doesnt look like I am the only one having the issue... any updates?

**Comment by dragoness411** [comment]
> So I am having issues with the program running. The bot works for a short period and then stops completely. It also varies, sometimes it wont even load up the stops and never shows any pokemon. Doesnt look like I am the only one having the issue...

> 

Ive been having the same issues for 2 days.

**Comment by Myxa80** [comment]
Yes. Same issue. But ingame same. Every few hours nothing. No stops and nothing to catch.
