### ISSUE TITLE
Some ideas 

### ISSUE THREAD

**Issue by AlbRk** [finndev/PokeBuddy#251]
I read a lot of "issues" about upgrades so I thought that it was a good idea to recap them here. Maybe this post will be used for status/new suggestions about upgrades.

I - Hatching eggs        [Pending] 
It could be awesome if the bot puts eggs in incubator. A new functionality with some parameters like priority set by the user and an option to use the 3 uses incubator or not.

II - Event order        [Pending] 
In the GUI, the last pokemon catch is at the bottom of the list and you always have do scroll down to see the last one caught. Maybe set the last pokemon caught on the top will improved our experiment.

III - Location bookmark         [Pending] 
A very useful functionality to allow users to choose where they want to bot without keep in mind the longitude and latitude.

IV - Pokeballs/GreatBall/UltraBall        [Pending] 
Every pokemon is caught with pokeballs, i think it could be great to catch high CP with Great/Ultra balls.

V - Languages        [Pending] 
I don't know how you save your text, json,xml what ever, maybe we can collaborate for a multi language version.

Finally, I want to thank the developers for their really good job.

**Comment by curtiola** [comment]
see #172
