### ISSUE TITLE
Status for PokeBuddy 

### ISSUE THREAD

**Issue by Miiwii** [finndev/PokeBuddy#253]
Hey guyz. I opend this for updates about PB . 
Im not an Admin but i think its better to have 1 Post where everyone can post some news about PB or things like that. (for example if its working )

Hope we ll get more infos soon!

Go PB!!

**Comment by Dumiiiiii** [comment]
Not working

**Comment by Rab89** [comment]
You'll find all updates here #218

**Comment by whoppster** [comment]
Its a bigger issue than what was first believed and hence it will take longer to solve.
There are a bunch of discussions going on all over (reddit, github etc).
One guy claims to have solved it but wont share, he got a C&D letter from Niantic.

**Comment by Vanethir** [comment]
Sorry, I don't have any status update for you so far. Once I know anything I will post it in #218 though. :)
