### ISSUE TITLE
FREE-BETA

### ISSUE THREAD

**Issue by ziomks** [finndev/PokeBuddy#26]
I can't log in 
it writes login failed

**Comment by finndev** [comment]
fixed

**Comment by aldokarendra** [comment]
I can't login too.. when i type FREE-BETA then i login, i got message "Login Failed" :(

**Comment by brijei** [comment]
check your spelling no spaces all capitals

**Comment by aldokarendra** [comment]
![screenshot 33](https://cloud.githubusercontent.com/assets/20703405/17269103/e9088220-5669-11e6-9250-b1499b030fa9.png)

**Comment by brijei** [comment]
maybe you have an old version. this problem was fixed and no one besides you is experiencing it.

**Comment by aldokarendra** [comment]
no, i have download newst version, but still that.
