### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Furlaa** [finndev/PokeBuddy#262]
The update is useless, couse pokebuddy give me the same error
-it can't catch and find pokemon 
-it can't farm pokestop...
Pls fix

**Comment by Dumiiiiii** [comment]
HEY BE PATIENT LA

**Comment by Vanethir** [comment]
Problem is still not solved. Check #218 for updates. The latest file is just a README file submitted by an user. :)

**Comment by cgerdon** [comment]
well the newest commit only fixed the readme.
the devs are doing an awesome job here providing us the bot for free. so please be patient!
