### ISSUE TITLE
whats going on?

### ISSUE THREAD

**Issue by SparkzZone** [finndev/PokeBuddy#263]
some bots are now coming back online and I was wondering when pokebuddy will be back as I would rather use this one cos I have donated to them

**Comment by MakaMate** [comment]
There will be a post no one really knows

**Comment by PromethiumFire** [comment]
There has been no updates as of yet for PokeBuddy. If other Bots are back online then that is a good sign. Updates will be listed here. [Here](https://github.com/finndev/PokeBuddy/issues/218)

**Comment by Miiwii** [comment]
https://discordapp.com/channels/208436903735853057/210530044768944130

ppl working on it but the problem is harder then they thought, 
Its more the just  -> unknown6

so just wait for more news
