### ISSUE TITLE
bot not working - since yesterday/today night.

### ISSUE THREAD

**Issue by msm2k11** [finndev/PokeBuddy#265]
Since this night the bot stop working. Have downloaded new repository but same problem. The bot only will transfer and envolve but farming pokemon or pokestops, not working.

Have tested on "Windows 7 x64" and "x86" also on "Server 2008 R2 x64".
Also Tested with "Google" and "PTC" Account.

Any info about this? Thanks.

**Comment by Vanethir** [comment]
check #218 for information and updates. :)

**Comment by msm2k11** [comment]
oh sorry!
