### ISSUE TITLE
Any News about Pokebuddy?

### ISSUE THREAD

**Issue by itzJOKINHA** [finndev/PokeBuddy#273]
Will it be ONLINE again? :+1:

**Comment by PromethiumFire** [comment]
For news and updates about PokeBuddy Click [here](https://github.com/finndev/PokeBuddy/issues/218). Alternatively click [here](https://github.com/finndev/PokeBuddy/issues/227#issuecomment-237614739) for Vanethir's General discussion post. Nothing new yet.
