### ISSUE TITLE
Pokebuddy not starting at all

### ISSUE THREAD

**Issue by Thomaschii** [finndev/PokeBuddy#277]
Hi.

Besides the API issue, my pokebuddy managed to start up once, then it didn't start up anymore. 
Firewall's off, no virus scanner that blocks it. Any idea what it could be that blocks the startup? Is java required to start pokebuddy?

Thanks.

NOTE: In my task manager "COM Surrogate" pops up for a few seconds, then disappears.

**Comment by futi666** [comment]
mine works fine, try to reinstall it

**Comment by Vanethir** [comment]
Did you check our [FAQ](https://github.com/finndev/PokeBuddy/wiki/FAQ)? :)

**Comment by Thomaschii** [comment]
Checked it, tried it, but didn't make any changes. How can I reinstall the bot? It's not under windows programs, neither I can find an uninstall file or something close to it.

**Comment by Krome333** [comment]
like other said .. just try to reinstall again !!

**Comment by rmarquez5** [comment]
The zip extracts to a folder. Delete the folder, reextract and start it again fresh.

**Comment by Vanethir** [comment]
By deleting it, loading new version and running PokeBuddy.exe once again.
If it doesn't work as well try to move PokeBuddy.exe from the Loader directory to the parent directory. (If you use the master directory)

**Comment by Thomaschii** [comment]
Moved it to the parent directory, problem solved. Thank you all for helping. Much appreciated!

**Comment by roy1988** [comment]
Pokebuddy is working now?

**Comment by Thomaschii** [comment]
My programme just starts now, nothing else yet #267
