### ISSUE TITLE
Best Pokeball

### ISSUE THREAD

**Issue by Kanutex** [finndev/PokeBuddy#282]
How does PokeBuddy use the best pokeball? Do I have to put 0 in Pokeball item to make sure Pokebuddy uses super/ultraballs?

Thanks

**Comment by Vanethir** [comment]
At the moment it's buggy and won't use Greatballs/Ultraballs at all. So you will get a catch error if you do not have any Pokeballs left. Might be fixed within one of the next updates.

**Comment by Kanutex** [comment]
Thank you so much, I hope it´ll be available soon :)
