### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by fordlol** [finndev/PokeBuddy#287]
[P - 16:56:23] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 16:56:30] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 16:56:36] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...

is all that keeps coming up for me when the bot is running any idea when this will be fixed?
thanks

**Comment by Vanethir** [comment]
Check #218 for updates, #227 for open Discussion. No ETA yet.
