### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by lmarley1994** [finndev/PokeBuddy#288]
Right,

so i downloaded the bot did everything properly and it comes up with no pokemon found and doesnt move. then it just keeps coming up updating, ive deleted and redownloaded the bot. can anyone help with this please?

**Comment by curtiola** [comment]
#218

**Comment by robstar109** [comment]
The bots down at the moment, look at the other posts for information on this.

**Comment by curtiola** [comment]
no bot will run until this project is done: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?sort=new
