### ISSUE TITLE
no transfer!

### ISSUE THREAD

**Issue by wilbak** [finndev/PokeBuddy#29]
tried resetting stop/start tried refreshing the app. and fresh DL no luck and its evolving the weakest pokemon as well two medium issues that needs be addressed!

**Comment by finndev** [comment]
try last version 0.0.3.6 please

**Comment by wilbak** [comment]
just did that still no result

**Comment by brijei** [comment]
try to redownload the .zip

**Comment by wilbak** [comment]
your silly and did not read

**Comment by wilbak** [comment]
opening new!
