### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by hajimesaitou** [finndev/PokeBuddy#291]
I put the bot in a location where it can reach 4 pokestops at the same time with lures and it's doing nothing. Not catching Pokes or even farming the Pokestops. 
What am I doing wrong?
Thanks.
![image](https://cloud.githubusercontent.com/assets/20848972/17422043/d49dbe62-5a84-11e6-8d96-e0d24794086b.png)

**Comment by Vanethir** [comment]
Check #218 for updates. No Bot is working right now. :)
Feel free to join #227 for open discussion.
