### ISSUE TITLE
not really new but i'm wondering when the bot will be fixed, and sorry for the bothering i know the devs are working on it, but my bot will transfer and evolve pokemon but it wont walk at all, so i'm wondering if that's the common issue or if i need to fix that myself.

### ISSUE THREAD

**Issue by aleksandr02** [finndev/PokeBuddy#293]

**Comment by curtiola** [comment]
see this thread for progress with the API: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?sort=confidence
see #218 after the API is figured out for pokebuddy news

**Comment by rogertai** [comment]
Thank you very much for hard working!
