### ISSUE TITLE
MY BOT WORKED THEN CLOSED!!

### ISSUE THREAD

**Issue by AhmadS12** [finndev/PokeBuddy#295]
I left the bot on then i went to the washroom *poop* when i came back i saw the bot farming some pokestops then closed 
![capture](https://cloud.github**usercontent.com/assets/15130678/17425614/4eac6baa-5a9d-11e6-9d0d-0d272ca1b23e.PNG)

**Comment by AhmadS12** [comment]
did this happen to anyone!! ^^^^^^

**Comment by curtiola** [comment]
i'd much rather see a screenshot the logs, so i know if it was actually recent or not, not trying to be rude but i am a skeptic, finndev told us he temporarily stopped the bot from making API calls yesterday, if it did actually work today for a bit i have no idea how or why lol

**Comment by AhmadS12** [comment]
@curtiola you got me ha it was a joke bored AF. Thanks for replying tho ;)
