### ISSUE TITLE
Visual Studio Issue

### ISSUE THREAD

**Issue by HalosSomerset** [finndev/PokeBuddy#296]
Bit of a newbie here, I tried running the program, but I keep getting an error stating that my Visual Studio license is out. Do I need a new license or is there another program than can run the XML Config file? Thanks.

**Comment by curtiola** [comment]
for 1:
no bot will be working until the API is figured out,
see this thread for progress with the API: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?sort=confidence
see #218 after the API is figured out for pokebuddy news
2: visual studios isn't required at all, if its an XML file you want to open, use notepad, to run pokebuddy just extract the zip, extract the second zip and then open pokebuddy.exe, but there's no point until it's fixed
