### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tomkeen12** [finndev/PokeBuddy#3]
I think you forgot to add the GNU (GNU GENERAL PUBLIC LICENSE v3) from the original project.
Added to this you could rename some of the original files atleast.

```
cat PokeBuddy.exe | strings | grep Datetime -i
DateTimeExtensions
```

**Comment by myo** [comment]
XDDDDDDDDDDDDDDDDDDDD

**Comment by myo** [comment]
the guy behind this repo is known for stealing content and getting away with it so I doubt he cares
