### ISSUE TITLE
issue with starting

### ISSUE THREAD

**Issue by LokidPhoenix** [finndev/PokeBuddy#32]
Hi,
I don't know, if its an problem on my side, or an pokeebuddy problem.
everytime i wanna start it, there came the short download sequence, then the windows close and after that, it happened nothing more.
Thank you! if someone could help

**Comment by finndev** [comment]
redownload .zip

**Comment by LokidPhoenix** [comment]
done it!... it works again! thank you

and thank you for your great work on PokeBuddy!
