### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by myrad81** [finndev/PokeBuddy#321]
Thanks to the people making the program possible and especially thanks for your patience as 400 freaking people fail to read more than one post and start asking if it works yet.  A butt ton of work and time has went into development and it is appreciated.  As for the people that are probably going to comment on this post and then create a post asking if the program is up yet.....  You are what's killing this entire environment of people.  Shut up and read a few posts before asking anything.  Sorry for the rant, but just so dang tired of seeing the same "why won't it work" post over and over.  It's free, it's fun, it will come out when it's done.

**Comment by myrad81** [comment]
As a side note, I know jack crap about programming and understood from the start the unknown variables were going to be tough.  Unless you have the skill to do the programming yourself do ask if it's done.  Instead show your wppreciation for what has already been done by minds greater than yours.

**Comment by xxsupawarriorxx** [comment]
i under stand thanking them but this is the issue section. i dont think you should be posting stuff like this in here

**Comment by SirFritzRCS** [comment]
Why not? It's a valid issue... By asking the same questions over and over, you prevent the devs from doing their work as they like to be known as responsive. Stop posting repeat threads, and the bot will be up quicker :)

**Comment by Kullimon** [comment]
100% right 

everyone is writing the same instead to read the other posts

**Comment by ectjunior** [comment]
botters like you make the game worst when it could be the best !

**Comment by SirFritzRCS** [comment]
^ What? Lol
