### ISSUE TITLE
omg its taking a while holy crap im just suprised not complaining

### ISSUE THREAD

**Issue by oOBlueArrowOo** [finndev/PokeBuddy#325]

**Comment by curtiola** [comment]
You should not be surprised, it's not an easy task, also accounts signing in with 3rd party applications using this early release of the API will be flagged by Niantic according to the devs in the discord chat, it's possible finndev is waiting for them to clean it up, I'd prefer it that way anyway lol have some patience and stop posting about it taking so long, and when it is ready, do not log in with an account you aren't willing to lose until it's confirmed safe

**Comment by iblisxjahwe** [comment]
since when are bots safe?

**Comment by bcmmbc122333** [comment]
The API was just finalized, the bot should be up in the next 24 hours

**Comment by roachhhhh** [comment]
what's the link to the discord

**Comment by curtiola** [comment]
It's on the api status reddit, but the channels are locked because of idiot spam and history on the important channels isn't publicly available, nobody can talk, they're working in a hidden channel

**Comment by 311guy** [comment]
Kinda sounds like complaining haha

**Comment by curtiola** [comment]
GMT +1, 1:30 - This API is not flag-proof. Any account using this API will easily be flagged as not playing through the official app. For now the devs have had enough of it and you can't blame them.

Altitude for example hasn't been fixed. Also all API requests will appear to Niantic to be coming from IOS users, this is wierd if it is matched with a device which normally runs Android. There is much to be done, but we have gotten a working API and with that our job is done, for now.

^ Latest important update on the reddit thread

**Comment by oOBlueArrowOo** [comment]
hey i said i wasnt complaining
