### ISSUE TITLE
New API released? 

### ISSUE THREAD

**Issue by SpartanNico94** [finndev/PokeBuddy#332]
Hi everyone,
On Reddit I found this discussion about pokemon go api at this [link](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/).

The creator of this discussion released new API today. I don't know if I'm doing a useful announcement but Pokebuddy's developers may find useful this project. The new API can be found at this link [Pokemon Go API](https://github.com/keyphact/pgoapi).

Thanks for your hard work anyway! 

I hope I was helpful.

**Comment by Rab89** [comment]
as far as im aware its not safe

**Comment by Mafia-Hitman** [comment]
You are way behind the curve.....everyone that does anything with pokemon go development has been helping/watching that thread on reddit...

Only problem right now is there are a lot of flaggable discrepancies with that API so it isn't very safe right now

**Comment by finndev** [comment]
Bot is updated now
