### ISSUE TITLE
I cant wait moreee! :'(

### ISSUE THREAD

**Issue by Juan44** [finndev/PokeBuddy#335]
I'm desperate :'(

**Comment by aryodegrave** [comment]
how many kids in this issue?
if you not kid, you should be patient!

**Comment by Juan44** [comment]
I have 16 :v

**Comment by Juan44** [comment]
Waiting :S

**Comment by crispas1** [comment]
I'm new, and i'm waiting too!! I've tried with necrobot and pokefarm and its too slow!!!

**Comment by Suzano-Sho** [comment]
If you can't wait then why are you still here?...

These obnoxious posts are starting to rub even me the wrong way, and I'm not even one of the devs...

**Comment by Deuxgod** [comment]
If you can't wait and you're 16 just get your ass up from the chair and go hunt them out in the streets. At your age I was never at home, specially not waiting for a bot for a game to be released.

**Comment by Sudiddo** [comment]
i guess its better for us to give our support for the team.. because it's an unpaid job.. so... GIVE UR BEST GUYS ! LOVE U SO MUCH ! #NOHOMO

**Comment by themonk666** [comment]
you can change the walk speed for necrobot just go in to the release(1),zip file the go to config then  to config.json scroll down till you find "WalkingSpeedInKilometerPerHour":  then change the number to 180 or what ever speed you want and it will work faster till pokebuddy is up and running quick

**Comment by finndev** [comment]
Bot is updated now

**Comment by ApurvShinde15** [comment]
guys its working
just start the bot and it will automatically update,i just started botting.

**Comment by ApurvShinde15** [comment]
Thanks finndev,Appreciate your work.Hatsoff to you devs
