### ISSUE TITLE
No Pokeballs, Level 0

### ISSUE THREAD

**Issue by naomi172839** [finndev/PokeBuddy#34]
The app was working fine earlier however now it shows that I have no items and that my level is 0.  When checking on the pokemon GO app this is not the case.  Software bug or Niantic cracking down???

**Comment by brijei** [comment]
update or try to restart your computer. It could be that the servers are offline. you can check the servers of pogo by searching it on Google.

**Comment by naomi172839** [comment]
well for whatever restart fixed it but still an odd issue... Thanks!
