### ISSUE TITLE
Unable to Open.

### ISSUE THREAD

**Issue by PokemonMaster101** [finndev/PokeBuddy#35]
Howdy all!

I have had no trouble the last couple of days but I am not able to open this app as of now, I have done the re-download and it's just not wanting to Open. If it matters I have also tried to Run it as Admin.

If you have any ideas how to correct this issue, let me know!

Thanks!

**Comment by brijei** [comment]
check your antivirus. doesn't it work afterwards? try to run with compatibility.

**Comment by efraim14** [comment]
Yes i have this problem too, already excluded the folder from my antivirus checking. After the update, it doesn't opened at all.
Running windows 10 here.

**Comment by PokemonMaster101** [comment]
@brijei Antivirus has had no issues with it before, it want's to load but isn't booting. How do you 'Run with Compatibility'?

@efaim14 I am running Windows 8.1 here, I had it working yesterday but now it seems to not want to boot at all. Came up with the Update Window 1 time than no more, might be an error somewhere.

**Comment by PokemonMaster101** [comment]
@efraim14 I am running Windows 8.1 here, I had it working yesterday but now it seems to not want to boot at all. Came up with the Update Window 1 time than no more, might be an error somewhere.

**Comment by brijei** [comment]
wich .exe are you using? the one from the map loader or the one from pokebuddy.zip inside pokebuddy-master.

**Comment by PokemonMaster101** [comment]
@brijei I have been using the one from the ZIP Folder, I did try the other one to see if it would work. No luck.

**Comment by brijei** [comment]
if you'd like I can take a look using teamviewer? you can contact me by telegram: @YourDestination or hamgouts: bencgeerds@gmail.com

**Comment by PokemonMaster101** [comment]
@brijei Does your download of PokeBuddy work at this moment?

**Comment by efraim14** [comment]
@brijei if you use the one from the zip, it will downloading the new update and then close. Afterwards, the exe doesn't respond at all when i tried to open it. Nothing happened.

**Comment by brijei** [comment]
yes perfectly.

**Comment by brijei** [comment]
I've run several scenarios and i came to the conclusion that there should already be a pokebuddy running in the background. if not try to close in the task manager: windows host process.

**Comment by efraim14** [comment]
@brijei already checked my task manager while running the pokebuddy. The pokebuddy suddenly disappeared after running around 2-3 seconds in my task manager, then nothing happened.

**Comment by brijei** [comment]
did you try to close windows host process?

**Comment by jasoncwp** [comment]
I have the same problem and found the follow error in windows event

Application: PokeBuddy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at PokeBuddy.EntryPoint.Main(System.String[])

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at <Module>.Main(System.String[])



hope it can help

**Comment by brijei** [comment]
download a clean copy from github. download the master. extract pokebuddy.zip inside the master and click yes to overwrite the current files. this should fix your error.

**Comment by jasoncwp** [comment]
yes, fixed by download the new clean copy

Thanks

**Comment by brijei** [comment]
your welcome

**Comment by efraim14** [comment]
@brijei thank you, its now working. but i received this log:
[P - 13:24:13] [Error] The PTC servers are currently offline.
does everyone having the same problem?

**Comment by brijei** [comment]
I use Google.  this error means that the pokemon club server down is.

**Comment by Smmw** [comment]
I reboot my computer and it works............Oh MY GOD.....

**Comment by josebks** [comment]
@brijei 
I'm in trouble is to help me .. ? add me on skype please dj.josecsm or let me know your contacts

**Comment by shahmanav97** [comment]
@brijei I download master and extracted pokebuddy.zip in master. It still does not start. Cant start through Compactibility mode too. Cant you connect through team viewer please?
