### ISSUE TITLE
Berry, Pokeball count stays at 0, also says level is 0

### ISSUE THREAD

**Issue by ShipplesOfficla** [finndev/PokeBuddy#37]
ive been running it and its great its levelled me up twice (to level 4) and collected 100 pokeballs but the only issue is that it says i have zero pokeballs and im level 0 . how can i make it read how many items i have.  it cant catch pokemon due to the fact it says i only have 0 pokeballs, even though as i already said when i check on my phone i have 149.

**Comment by brijei** [comment]
update or try to restart your computer. It could be that the servers are offline. you can check the servers of pogo by searching it on Google. for some users it was fixed by running troubleshoot compatibility.

**Comment by ShipplesOfficla** [comment]
That worked haha wow I'm embarrassed I didn't think of something so basic, thank you!

**Comment by brijei** [comment]
your welcome
