### ISSUE TITLE
updating UI.

### ISSUE THREAD

**Issue by Bruce-Dillon** [finndev/PokeBuddy#381]
Sorry, really new to most of this. probably a simple fix just not sure how. I already installed a fresh copy of the files.

Just keeps updating UI, no changes at all after 10~ minutes.
[https://gyazo.com/6a5d2537e6e59dc9943a49460b3603dd]

**Comment by IamDeric** [comment]
Do you have a pokestop nearby?

**Comment by Bruce-Dillon** [comment]
Yeah i was using the default location, should be near lots of pokestops. do i need to hit level 5 and select a team first?
