### ISSUE TITLE
Stuck on [UI] Updating

### ISSUE THREAD

**Issue by The-Promised-End** [finndev/PokeBuddy#386]
I'm able to log in, and I can see my stardust, but my experience, pokeballs, and berries count remain 0, and it's showing the "[UI] Updating..." repeatedly.

**Comment by curtiola** [comment]
Any pokestops nearby? It'll do that if it can't find one

**Comment by The-Promised-End** [comment]
I'm just using the default starting location.

**Comment by curtiola** [comment]
Oh, not sure where that is, it'll probably get you softbanned if you change it to a far away spot now though lol I use central park ny, I'm on mobile right now but Google could tell you coordinates

**Comment by kenwang911** [comment]
im have the same issue on it. anyone can help.
I try close and open again, i did deleted and downloan it all again, but still the same issue.
any one can help....

**Comment by curtiola** [comment]
Change from the default location? If there are no stops nearby it'll do that, no idea where the default is but I never have this problem in central park ny

**Comment by kenwang911** [comment]
I had try few other loacation, syney, newzealand, but still the same......:(

**Comment by curtiola** [comment]
Hm I don't know how to fix it, sorry

**Comment by kenwang911** [comment]
thanks for your help anyway......

someone else can help????

**Comment by kenwang911** [comment]
@The-Promised-End   have you fix this issue yet?

**Comment by The-Promised-End** [comment]
@kenwang911 Nope

**Comment by kenwang911** [comment]
@The-Promised-End  try restart your computer......I did try and sorted....:)

**Comment by The-Promised-End** [comment]
@kenwang911 Yes! Thank you!
