### ISSUE TITLE
Pokestops won't appear?

### ISSUE THREAD

**Issue by Bruce-Dillon** [finndev/PokeBuddy#388]
Stuck on Updating UI, because no pokestops are visable was just useing the bot in this area plenty of stops, program had gotten closed, re-opened and now there are no poke-stops?

**Comment by curtiola** [comment]
Strange, could be the Niantic servers are unstable, couldn't say for sure what the problem is

**Comment by barbaricacidman** [comment]
when the program reopened did your virus scan block something? i had problem with mine and it was part of the program being picked up as trouble

**Comment by Bruce-Dillon** [comment]
that is a possibility, turned everything off after the restart, so maybe.
