### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by SirFritzRCS** [finndev/PokeBuddy#394]
I cannot download the .zip... Not having firewall or connection issues, it just wont let me download. Any suggestions?

**Comment by SirFritzRCS** [comment]
Adblock stopped it. Solve the issue.

**Comment by SirFritzRCS** [comment]
Annnnnd zip stops downlaoding at 99% and says "Network issue"... Wtf?

**Comment by IMdrew** [comment]
Lol

**Comment by ThalesEu** [comment]
Disable your anti-virus (worked for my).

**Comment by SirFritzRCS** [comment]
Anti-virus turned off, not using proxy, adblock off, and anytime I try to download it I either get a page redirect showing "Cannot display page, check firewalls and internet connection etc etc", or it starts downloading and when almost complete it says there's a network error. I had the version from before niantic's api change, why can't I download now??
