### ISSUE TITLE
[UI]Updating.......

### ISSUE THREAD

**Issue by kenwang911** [finndev/PokeBuddy#396]
does anyone have the same issue with me still
"[UI] Updating........
Keep repeat and repeat....

did try delete and download, did try chance location, did try restart it more than 5 times, It still the same...

:(

Please help.

**Comment by curtiola** [comment]
Is it possible that it doesn't have permission to access your network? Maybe run as an administrator would help, I'm just guessing lol

**Comment by kenwang911** [comment]
Just tried what you suggest, but still the same。。。。：（

**Comment by IamDeric** [comment]
To far from the pokestop?

**Comment by curtiola** [comment]
Hmm, try copy pokebuddy.exe and paste it in the pokebuddy-master folder, then run as admin

**Comment by kenwang911** [comment]
did change few locations, don't think too far away from the pokestop...

**Comment by kenwang911** [comment]
@curtiola  did try what you said, but....no luck.......:(

**Comment by curtiola** [comment]
Maybe it's a firewall? I wish I knew more, sorry lol

**Comment by kenwang911** [comment]
@curtiola  Thanks for your help anyway......:)

**Comment by kenwang911** [comment]
All Sorted...... please close topic..........thanks for all your help.:)

**Comment by curtiola** [comment]
I'm happy you got it working, also you can close the issue yourself @kenwang911

**Comment by kenwang911** [comment]
@curtiola  thanks.....
