### ISSUE TITLE
having problem with login buddy 

### ISSUE THREAD

**Issue by KaChan1031** [finndev/PokeBuddy#40]
HELPPPP
was using fine last night about 5 hours.but starting from this morning login buddy it show.
[P - 15:06:09] Attempting to Login...
[P - 15:06:09] Logging in with method: Google as Auth Provider
[P - 15:06:09] Doing Google login...
[P - 15:06:10] [Error] GoogleAuthError: CaptchaRequired
[P - 15:06:10] Failed to login.
[P - 15:06:10] Stopping...
please Help.

**Comment by brijei** [comment]
wait 5 minutes and it should work again.

**Comment by KaChan1031** [comment]
It still not working .
Same problem.

2016年7月30日 下午3:55 於 "brijei" <notifications@github.com> 寫道：

**Comment by brijei** [comment]
I had it one time change your password should work inmedietly
