### ISSUE TITLE
Pokemon and Items missing???

### ISSUE THREAD

**Issue by stas5678** [finndev/PokeBuddy#401]
The Bot does not seem to be able to detect my pokemon, trainer level, or items, which is preventing me from transferring pokemon or recycling items and is limiting the effectiveness of the bot. I'm confused if anyone else has this issue or just me? Screenshot:
![image](https://cloud.githubusercontent.com/assets/20826573/17465971/ca2bf9a4-5cd1-11e6-8b9c-12eb01986aa2.png)
oH THIS isn't anything too urgent, I know the dev just did a lot of hard work so I'm looking for something I can fix myself, but I don't have any coding experience at all so if there is a manipulation I'll try to find it

**Comment by curtiola** [comment]
Not sure what the problem is, a couple others have the same issue but the majority don't, could it be a firewall blocking network access? Maybe run as an admin? Idk I've suggested these and other possible fixes to the others but they had no luck.. lol

**Comment by curtiola** [comment]
One other just fixed this by restarting his pc, maybe that will work for you

**Comment by curtiola** [comment]
Haha ^ yeah xD thanks @kenwang911

**Comment by stas5678** [comment]
hmmm I'm going to try it, that you for the advice:)

**Comment by kenwang911** [comment]
we here to help each other....

**Comment by stas5678** [comment]
Awesome, it works perfectly now, thanks guys!

**Comment by nielsm123** [comment]
I'm gonna try it too :dancer:
