### ISSUE TITLE
Still can't use the bot :3

### ISSUE THREAD

**Issue by haux1231** [finndev/PokeBuddy#409]
Downloaded the latest version still can't see Pokemon or Pokestops nearby :3
Any possible solution? I really cant think of anything at the moment. Also, Sorry if this is being reposted

**Comment by PromethiumFire** [comment]
Is this your first time trying PokeBuddy after the new API?

**Comment by haux1231** [comment]
Not really. I've start stop multiple times and reinstalled the app about 5 times too @PromethiumFire

**Comment by PromethiumFire** [comment]
Are you loading up the correct PokeBuddy? You may be accidentally be trying to load the old version.

**Comment by curtiola** [comment]
Try restarting pc, this helped 2 others so far today

**Comment by haux1231** [comment]
@PromethiumFire Well, I am extracting the .zip that was uploaded about 9 hours ago? Tell me if I am doing something wrong :3
@cutiola Uhh, Alright I guess. I'll give it a go.

**Comment by haux1231** [comment]
Nope. Not working @curtiola

**Comment by SirFritzRCS** [comment]
I keep having an issue where, during launch update, it stops on "Downloading pokebuddy.core.dll" and gives me an error... It still lets me launch but keep walking around, not to any pokestops, not catching any pokemon. Is this the issue you're having?

**Comment by PromethiumFire** [comment]
Apparently the servers are being unstable. I too, am now experiencing the same issue as you. Everything was fine 30 mins ago. @haux1231

**Comment by RawPassion** [comment]
http://ispokemongodownornot.com/ 

shows there was a hiccup about 30 minutes ago but everything should be good on our end. Note that there was a new launch in Brasil, so things may be a bit iffy

**Comment by curtiola** [comment]
Yeah I imagine the load is huge, they shut down bots and maps to ease server load so they could release to Asia and south America, and then the scrapers got their API back haha I believe it's an inrush of connections Niantic didn't expect

**Comment by PromethiumFire** [comment]
Everything is fine again now.

**Comment by haux1231** [comment]
The app launches just fine. I can log in and stuff. I hit start and the lil red '+' starts moving tho I dont have any pokestops or pokemons nearby. I've read almost all the issues since the new update and I still can't find a solution @SirFritzRCS

**Comment by haux1231** [comment]
Uh well alright. I'll give it a go later in the day then. Till then I might as well get started with JustCause 3
Thank you anyway people :D
P.S Goodjob Dev's 😁

**Comment by PromethiumFire** [comment]
Close PokeBuddy. Delete PokeBuddy, delete any copied download files there is. Then go here https://github.com/finndev/PokeBuddy, click clone or download, click download. Then extract the files and try running PokeBuddy again. Enter FREE-BETA then sign into your google or Pokémon account. Enter your desired co-ords then click start. If the problem still persists then its probably due to Niantics servers.

**Comment by Giammaofwar** [comment]
I had too and I resolved by making an exception for the pokebuddys folder in my antivirus, my antivirus was blocking it

**Comment by haux1231** [comment]
Thank you all of you for the help :D
Solved the problem by adding the pokebuddy folder as an exception :)
