### ISSUE TITLE
Bot started but no pokestops nearby.

### ISSUE THREAD

**Issue by Myxa767** [finndev/PokeBuddy#41]
Bot started to work. Transferring bad pokemons but can't find any pokestops near. Map also empty. So bot just stuck on start place and doesn't move at any directions.

**Comment by semplex111** [comment]
same problem here..

**Comment by brijei** [comment]
this means the pogo servers are down. nothing to worry about ;)

**Comment by Myxa767** [comment]
"this means the pogo servers are down. nothing to worry about ;)"
actually not. i can login from my phone and everything works fine.

**Comment by brijei** [comment]
then the pokestop should appear again. there are more servers then one :) if 1 is down that doesn't mean the others are down too.

**Comment by perfidiousdan** [comment]
Same problem no more pokestop. The game work well on my phone but pokebuddy is down.

**Comment by perfidiousdan** [comment]
Im a sad panda now........

**Comment by BobNiko** [comment]
+1
No pokestops on the map =(

**Comment by dominikof** [comment]
No pokestops ((((

**Comment by furyshot00** [comment]
is there any quick fix for the soft ban???

**Comment by furyshot00** [comment]
![image](https://cloud.githubusercontent.com/assets/20949827/17554919/e9f2c7de-5f3f-11e6-85c2-cbb4bdc6dd7e.png)

is this a soft ban because im not seeing any pokestops nearby

**Comment by Sartorius1997** [comment]
I'm having the same problem. It looks lke it's not logging in properly

**Comment by T2HotZero** [comment]
Yeah I have the same issue, did the steps others listed and did nothing for me. Sometimes it works for a few min and then stops. If anyone have a real fix please let us know

**Comment by DUSKvsDAWN** [comment]
Lemme bump this. Since today got the same problem.
