### ISSUE TITLE
Does the transferring bad pokemon work? I am afraid to try this function, cause I have lost many good duplicated pokemons using the previous version

### ISSUE THREAD

**Issue by Smmw** [finndev/PokeBuddy#410]

**Comment by curtiola** [comment]
No it will transfer all but the highest cp, you can mark them as favourite on your mobile to stop it from transferring though

**Comment by Smmw** [comment]
I read from the previous post. it says mark as favorite will not work either.

**Comment by curtiola** [comment]
Oh damn, well thanks for letting me know, I suppose manual transfer is the best way then

**Comment by AIG1992** [comment]
Mark as favorite does work. I haven't lost any of my duplicates.

**Comment by curtiola** [comment]
Lol thank you, I'll have to try it myself sooner or later, I believe it should work, it worked before

**Comment by Smmw** [comment]
Do i need to choose "do not transfer selected" or just mark the pokemons as favorite or do the both?

**Comment by curtiola** [comment]
Do not transfer list is bugged, for now marking as favourite is the only way

**Comment by Smmw** [comment]
ok thanks!
