### ISSUE TITLE
Best coordinates to catch rare pokemons?

### ISSUE THREAD

**Issue by Althirion** [finndev/PokeBuddy#412]
I've heard San Francisco and Sidney are good to catch pokemons, but can you be more specific please!
I'm bored of Santa Monica Prier

**Comment by curtiola** [comment]
Search Google for nests, there are dratini nests in SF, the wiki will give you coords

**Comment by RawPassion** [comment]
http://pkmngotrading.com/wiki/Nests

This should help, cheers :)

**Comment by curtiola** [comment]
But honestly this is the issues section for a bot, you should take this kind of question elsewhere, or at least to the general discussion thread, the devs have enough to filter through already

**Comment by myrad81** [comment]
Please close out your post.  Issue is resolved

**Comment by myrad81** [comment]
Lmao nevermind you done it as I hit comment
