### ISSUE TITLE
Won't transfer pokemon/show items

### ISSUE THREAD

**Issue by Bruce-Dillon** [finndev/PokeBuddy#419]
Having an issue, I keep getting stopped because my pokemon slots are filled, it won't transfer all the shit pokemon im getting, any ideas? 

[https://gyazo.com/0133d22567446f7922f81d419289000e](url)

**Comment by curtiola** [comment]
Link won't work for me, not sure why it's not transferring, I haven't run into that problem, try restarting?

**Comment by Bruce-Dillon** [comment]
Strange, it is showing my pokemon at 0/200 and my items at 0/250, i have all the lowly mons unchecked to be sent, and still isn't working or loading the list.

no luck restarting. Thanks for the idea though.

**Comment by curtiola** [comment]
Huh, sounds like it's not connecting to your account, could be server problems

**Comment by Bruce-Dillon** [comment]
Was thinking that as well, just thought it was strange that it was able to catch them, but not load the list, maybe I'll try a clean install (not tech savvy at all) think that would do anything?

**Comment by curtiola** [comment]
Oh didn't know you could catch lol well I'm not sure if that would help or not either but it might

**Comment by Bruce-Dillon** [comment]
hmm Yeah thought it was kinda strange it has me listed as level 0 (I'm 15) and still not showing them damn mons, Strange. Should i keep open and hope for a Dev response?

**Comment by curtiola** [comment]
Yeah maybe someone else will know what to do, I know it's a longshot but maybe restart the pc? Lol..

**Comment by Bruce-Dillon** [comment]
HAHA!! good Longshot man, restarting fixed it right up, big kudos's to you brother!
