### ISSUE TITLE
Ploblem Open pokebuddy.exe

### ISSUE THREAD

**Issue by Nitipoom1997** [finndev/PokeBuddy#42]
http://i1249.photobucket.com/albums/hh502/Poom_Nitipoom/13844251_1608708369426615_1327549378_o_zpscabmqwjt.jpg
^
^
Image link

**Comment by brijei** [comment]
download master from github again. extract pokebuddy.zip inside the master and click yes replace all. this should fix it. if it doesn't try running troubleshoot compatibility

**Comment by ragger10** [comment]
I have the same problem.. I cant fix it no matter what. Pokebuddy exe. just stops working and shuts programe down clicking on it.  i have tried d/l new zip and tried on another com as well.. it just wont start.  The zip needs to be fixed or someone needs to provide detailed info on how to go about on a fresh install

**Comment by wilbak** [comment]
go in to your extracted files folder and make sure all the files that are in the description match what you have in your folder if not then your AV might of flag a file and stopped it from being placed in the proper place if it has then we will go from there

**Comment by brijei** [comment]
indeed check your anti virus
