### ISSUE TITLE
Pokebuddy (No Pokemon nearby/There are no pokestop nearby!)

### ISSUE THREAD

**Issue by 49gallegos** [finndev/PokeBuddy#423]
So I am very thankful for the Dev's hard work to get the API updates and for finndev to be able to release a new pokebuddy update! However, I get this problem where after farming pokestops and Pokemon for 5-7 minutes it says [Catch Pokemon] No Pokemon nearby [Farm Pokestops] There are no Pokestops nearby! Is this just because there aren't any pokestops to walk to nearby and I need to stop and start it at a different location or is there another way? Thank you to anyone who helps out! :D

**Comment by JShenpai** [comment]
Also having this problem

**Comment by Giammaofwar** [comment]
Disable your antivirus or make an exception for the pokebuddys folder, I had too

**Comment by 49gallegos** [comment]
@Giammaofwar I made an exception for pokebuddys folder but it didn't help :(, thx for taking the time to comment anyways

**Comment by trueeblood** [comment]
I disabled antivirus and still did not work still gives the same error

**Comment by 49gallegos** [comment]
Hhhm it looks like after a while it will walk back to original location to farm more, sweet!

**Comment by alva1018** [comment]
Not the antivirus issue. 
IT IS THE IP BAN!!
Occurred several times and finally found out. 
I have two available connections with different public IPs. Switch to another when one got banned immediately fix this problem. 
Also noted that the IP will be banned for only a few hours.
