### ISSUE TITLE
suck on login

### ISSUE THREAD

**Issue by konchim** [finndev/PokeBuddy#43]
[P - 16:13:53] Feel free to donate to (PayPal): support@epicdevs.de (make sure to email me afterwards)
[P - 16:13:53] --------------------------------
[P - 16:13:55] Attempting to Login...
[P - 16:13:55] Logging in with method: PTC as Auth Provider

no respone forever

**Comment by brijei** [comment]
do you use ptc or google

**Comment by konchim** [comment]
both account also.

**Comment by brijei** [comment]
no try Google make sure you cross the box Google and offcourse fill in your information don't leave it empty

**Comment by konchim** [comment]
I had work before. but not work today..

**Comment by brijei** [comment]
where are you from?

**Comment by konchim** [comment]
Canada

**Comment by brijei** [comment]
Google login server is down

**Comment by konchim** [comment]
I had check that the pgorelease.nianticlabs.com/plfe/234 had be deleted.
