### ISSUE TITLE
Error: please set a proper GPS location

### ISSUE THREAD

**Issue by demitank** [finndev/PokeBuddy#469]
any location i enter seems to be invalid. Tried with different accounts and the result is the same.
![capture](https://cloud.githubusercontent.com/assets/20900904/17473488/2bd7783e-5d6a-11e6-8953-7af1fd63b473.PNG)
![capture1](https://cloud.githubusercontent.com/assets/20900904/17473489/2bdf36b4-5d6a-11e6-8005-c79f9acfe234.PNG)

**Comment by Deuxgod** [comment]
Change the altitude to 17 and try again

**Comment by pokemonloverx333** [comment]
i have no altitude use in every account , try to delete altitude from your shit , if it doenst work , do what i always do , open folder delete settings.json reupdate and re enter everything , also look for your firewall and anti virus to be stopped

**Comment by pokemonloverx333** [comment]
what is altitude btw ? are u always flying or what ?

**Comment by Deuxgod** [comment]
Not all points on earth have the same altitude. For Central Park the altitude of the terrain is 17. If you go farm to Everest of course the altitude is much higher. Coordenates work on a 3 dimensional axe, latitude, longitude and altitude.

**Comment by pokemonloverx333** [comment]
well i never used altitude , no matter where i was , i just used coordinates i got by google maps and clicking somewhere , never showed me altitude , and worked perfectly for me all time

**Comment by demitank** [comment]
changing altitude didnt work.
