### ISSUE TITLE
Transfer bad Pokemon

### ISSUE THREAD

**Issue by iksws** [finndev/PokeBuddy#483]
The check Transfer bad Pokemon not work, all pokemons are been tranfered!!!!!!!!!
have 99 pokemons and catch 109 pokemons and bot trnasfer 109 dammit :(

its a bug?

**Comment by myrad81** [comment]
No, if you catch a pidgey and already have a pidgey it will transfer the one with the lowest cp.

**Comment by Thomaschii** [comment]
This makes no sense that they keep one of each kind. Maybe the devs could make an option to transfer specific pokemon and leave the other pokemon in your inventory? @finndev

**Comment by iksws** [comment]
Not calculate more IV to transfer?
I want 3  Vaporeons for example, I have 2 need more 1 good IV evee to envolve and bot transfet ALL!

**Comment by myrad81** [comment]
You could log in on your phone with GPS disabled and mark pokemon you wish to keep as favorites then they won't be transferred

**Comment by iksws** [comment]
No! my 99 pokemons have GOOD IV and bot don't transfer any, but new pokemons caugths the bot transfer all, the bot don't check more if good or bad to envolve more.

**Comment by myrad81** [comment]
Ok a little loss in communication.  Are you saying it is transferring everything you catch?   And as far as I know the bot does not use IV to decide what to keep it uses only CP

**Comment by iksws** [comment]
Yes bot transfer ALL!

**Comment by myrad81** [comment]
Ok, it should transfer all but the strongest.  So far there is no way to get it to keep the three strongest eevee or the two strongest vaporean.  If you want to have more than 1 of any pokemon you will have to u click transfer pokemon option

**Comment by rmarquez5** [comment]
A tip for everyone using the Transfer option on Pokebuddy. Mark the ones you want to save a Favorite (star). It won't transfer anything that is marked as a Favorite, so you can save your army of Vaperons easily and still take advantage of it transferring your Pigeys. Works great for me. A little tedious, but I'm working around what the bot can and can't do. Try it!

**Comment by iksws** [comment]
Before the new API bot left all strong, now it transfers all.
I had  6 evees strong and old bot not transfer, now if  I catch good evee 600~700 CP the bot tansfer. :(

**Comment by rmarquez5** [comment]
I don't think the bot ever transferred just the lower CP Pokes. I'm pretty sure it always saved just the strongest one and transferred the rest. Again, marking a Poke as a favorite will work around this. Give it a try and you can save multiples easily.
