### ISSUE TITLE
Will I get banned if I change my location?

### ISSUE THREAD

**Issue by FlyingFish10** [finndev/PokeBuddy#486]
I want to move to a spot with higher xp/hr but I don't want to get banned

**Comment by akakk911** [comment]
no as long as you dont teleport and give it like 2 hours between switching. im farming in canada france tokyo   lol

**Comment by iksws** [comment]
If you teleport so far or change country fast you go get SOFTBAN 4~8 hours!
wait 1 day to change country! not teleport to far and you go ok!

**Comment by iksws** [comment]
PS: you can remove softban simply tap the location of pokestop 30 ~ 40 times

**Comment by FlyingFish10** [comment]
How do I not teleport when changing the location with pokebuddy?

**Comment by akakk911** [comment]
if you go to settings  and walk settings you can see a check box in there.

**Comment by FlyingFish10** [comment]
Okay, teleport isn't checked, so it'll just walk from new york to tokyo?

**Comment by r0nalxd** [comment]
It still teleports. You need to change locations only after you've waited (no bot running or logging in via mobile) a few hours (travel time). Then you can enter new coordinates in Pokebuddy. If you do get softbanned, the bot will automatically unban you within 5-10 minutes by using pokestops (succes -> Received XP: 0). When the pokestops start giving XP again, the ban is lifted.

**Comment by akakk911** [comment]
no you have to change coords download  (map coordinates) app from google play or app store go in it and change the readings to decimal degrees, pick location and just punch in the #  note that when u stop at any pont it will start again at the punched in coords

**Comment by FlyingFish10** [comment]
Is there any more powerful punishment than I softban?

**Comment by akakk911** [comment]
full ban but thats rare  and you would have to push the bot to its limits
