### ISSUE TITLE
LOGIN FAILED

### ISSUE THREAD

**Issue by cheark08** [finndev/PokeBuddy#49]
I cant log-in in the FREE-BETA Account. what should I do

**Comment by Vanethir** [comment]
There are 2 possible solutions for this problem:
 
1. Make sure there is no space behind "FREE-BETA". Spaces are recognized and won't be accepted.

2. Check your Computer datetime. Make sure to use the real time. 

Hope one of these solutions will work for you.

**Comment by cheark08** [comment]
I will attached here my screenshot. computer time is correct and the
spelling, spacing is correct also. but same problem will occur.

**Comment by brijei** [comment]
you have an old version. download the master from github. extract the pokebuddy.zip. within the master and click yes to all. should be fixed then.
