### ISSUE TITLE
cant sigin with username FREE-BETA

### ISSUE THREAD

**Issue by Xo9** [finndev/PokeBuddy#491]
Icant sigin poke buddy with FREE-BETA
Please fast respon :'(

**Comment by Xo9** [comment]
Help please

**Comment by Razdavitel** [comment]
Have you tried downloading a clean copy again and just replace your settings file? Also what happens when you enter "FREE-BETA"?

**Comment by str3ck** [comment]
I'm having the same issue.  I downloaded a fresh copy of the app onto a new computer.  When first launching that app, there is a popup when the update wizard tries to run, that says "Failed to get updatedata. GitHub may be down?"

If you hit the OK button and go to login, with FREE-BETA, you just get a "Login failed" message in the window.

**Comment by Razdavitel** [comment]
Try to disable your firewall, is the problem persistent on an other computer too? I have tried a fresh copy too and it seems to be working just fine.

**Comment by Xo9** [comment]
Ok im trying

**Comment by Xo9** [comment]
Just same login failed

**Comment by Razdavitel** [comment]
It has to be something on your end. Are you sure you don't have an old version? I cloned a VM and tried to run it there and it worked perfectly. Is it possible to try on a different network? Perhaps a VPN?

**Comment by Xo9** [comment]
My pokebuddy is old version

**Comment by str3ck** [comment]
mine is still doing the same thing, even though it is the newest version from this morning.  However I'm at work and it may well be the firewall, so I'll check again when I get home later.

**Comment by Dj-jom2x** [comment]
i know why due to cloudflare :) if you all sending same data at the same time randomly selected people will got cloudflare guard page ... :) here's the future website : pokebuddy.gg

try to add this on your host file

200.74.241.201 pokebuddy.gg
200.74.241.201 www.pokebuddy.gg

:) same issue in d3d cheats loaders xD fuck cloudflare .. also in hake.me xD

soon "FREE-BETA" will end right ? because your site tells me that i need to pay it to get it xD

**Comment by str3ck** [comment]
any sites that want money for this app are scams.  the app even says so

**Comment by Dj-jom2x** [comment]
well if you use wire shark login goes to this url : www.pokebuddy.gg

**Comment by Rab89** [comment]
please dont post links to unknown sources.... Thanks

**Comment by finndev** [comment]
Please sync your time

**Comment by Xo9** [comment]
Ok

**Comment by mcmagic1** [comment]
is there a solution in LOGIN FAILED on POKE BUDDY now need your response sir. thanks

**Comment by Dj-jom2x** [comment]
1 thing :) unpack and get rid of the login feature :) works great :)

**Comment by jhaynickz0717** [comment]
the username FREE-BETA can't access the pokebuddy, help me please! it always says log in failed

**Comment by akdago** [comment]
It was working great up until an hour ago for me but also lost is. doesnt even attempt to login with FREE-BETA
