### ISSUE TITLE
Live Location screen bug

### ISSUE THREAD

**Issue by r0nalxd** [finndev/PokeBuddy#498]
![image](https://cloud.githubusercontent.com/assets/20835379/17489191/37cfaa52-5d9d-11e6-990e-bc365e367fe9.png)

When running PokeBuddy, I can't see the Live Location map anymore (see printscreen above).
Sometimes a restart works. Also, when revisiting a location on the map that was not affected by the bug, the map is viewable.

**Comment by Rab89** [comment]
your lat and long is 0 thats basically the south pole lol no wonder nothings showing

**Comment by r0nalxd** [comment]
Yeah, sorry, should've posted one with the bot actually running:
![image](https://cloud.githubusercontent.com/assets/20835379/17489651/68ffe6c6-5d9f-11e6-83bb-759b3185b77a.png)

**Comment by Rab89** [comment]
Im sorry but ive never seen this problem before its definently a minor gps bug.
is everything else functioning properly??

**Comment by r0nalxd** [comment]
Everything else works fine, except for the already known Do Not Transfer bug and the Always Catch bug

**Comment by Razdavitel** [comment]
I had this in the beginning. It fixed itself after like an hour of runtime.

**Comment by r0nalxd** [comment]
Running it longer didn't fix it, runtime was 4hrs before I attempted a restart to fix it

**Comment by r0nalxd** [comment]
Seems to have been fixed in the 0.7.7.7 update
