### ISSUE TITLE
Soft Ban

### ISSUE THREAD

**Issue by Energex22** [finndev/PokeBuddy#5]
Seems like i catch a pokemon, and then i get soft banned each time i'm using your program.. but other then that, pretty dope!

**Comment by Vanethir** [comment]
@Energex22 Are there any other Pokebots running simultaneously (probably in the background, could try to reboot), are you still logged in with any other device or did you teleport a huge distance (>10km) after starting the porgram?

If none of these questions is true: Can you provide your console entries (and probably settings) as additional information? Should help the developers to trace back the error. :)

**Comment by Energex22** [comment]
I do have a version of necro bot on another account, but i did try closing it and only having pokeBuddy running.. and i have a notepad i keep updated where i am at before i close the bots... Sometimes i catch one maybe two, and softban.

**Comment by Bayramklc** [comment]
Man pokestop 50 spin unbanned or quikspin used

**Comment by Vanethir** [comment]
@Energex22 still having problems?
