### ISSUE TITLE
Join the team

### ISSUE THREAD

**Issue by TheUserCB** [finndev/PokeBuddy#501]
Hello, my nickname is TheUser, I understand programming as well, here are some of my work, https://www.youtube.com/channel/UCnJhiQVXinf1eRZ9hgk_p4Q/videos, I like you also work with games, and understand the "bot "as you can see in this video where I simulate a connection to the game just using my program: https://www.youtube.com/watch?v=iYABYtGSlg8. I would like to join the team and help you develop bots, guarantee worth having me on the team.

**Comment by curtiola** [comment]
Finndev has an email address, you can see it in the bot log when you first start the program.

**Comment by TheUserCB** [comment]
Sorry but I could not find the email. Can you tell me the same?

**Comment by TheUserCB** [comment]
And excuse me for bad English, I am Brazilian and I am using Google Translate.

**Comment by curtiola** [comment]
When you open pokebuddy it's in the logs, says something like "make sure to email me if you donate"
I'm not on my pc right now so you'll have to find it

**Comment by TheUserCB** [comment]
Thanks.

**Comment by curtiola** [comment]
No problem, would you mind closing the issue? There are a very large number of posts for Finndev and Vanethir to filter through already.

**Comment by TheUserCB** [comment]
I'll close, but before I could answer a question?

**Comment by KillerSpecht** [comment]
Finndev`s email address  **support@epicdevs.de**

**Comment by TheUserCB** [comment]
Thanks, I'm sending the email.
