### ISSUE TITLE
Can't name my character

### ISSUE THREAD

**Issue by FlyingFish10** [finndev/PokeBuddy#503]
I started a new account with the bot, and now when I logged into my phone to give it a name, it says "Server Error" every time I try to name it. What should I do? I can't get into my account!

**Comment by curtiola** [comment]
At least it was new lol make another one but sign in on your phone first

**Comment by FlyingFish10** [comment]
No it's level 27 now after botting for a day

**Comment by FlyingFish10** [comment]
I can't sign another account in because it's stuck on naming, what do I do? Is there any way to force it to be named

**Comment by curtiola** [comment]
Sorry I don't know how to force the name or anything like that, but you can just end the app and sign out when it's starting up next time to make a new account, or try the same one if you have tried restarting the app yet lol
