### ISSUE TITLE
Hatching  eggs through pokebuddy

### ISSUE THREAD

**Issue by 49gallegos** [finndev/PokeBuddy#507]
So I noticed that the speed that pokebuddy moves around seems too fast for Pokemon go to gain km on eggs. Does anyone know what speed pokebuddy needs to be set at for eggs to be hatched and gain km in game? Thanks

**Comment by curtiola** [comment]
Some say the max is 19 and some say 15, idk, I go 11

**Comment by 49gallegos** [comment]
@curtiola Does 11 work for you? And thank you

**Comment by curtiola** [comment]
Yeah 11 works to incubate them

**Comment by 49gallegos** [comment]
@curtiola alright thank you
