### ISSUE TITLE
Can't name my character

### ISSUE THREAD

**Issue by FlyingFish10** [finndev/PokeBuddy#513]
Everytime I try to name my character on my phone I get a "Server Error." I'm locked out of this account and it's level 27!! help!!

**Comment by curtiola** [comment]
If you didn't name your character before you started catching pokemon you're probably screwed, sorry to say but games don't like it when things are way out of order, and you skipped the tutorial

**Comment by FlyingFish10** [comment]
Redownloading the app worked.. ya butt
