### ISSUE TITLE
Help with status: CatchError

### ISSUE THREAD

**Issue by AkenoYukihime** [finndev/PokeBuddy#523]
[P - 13:31:24] [Recycling Items] Recycling: 7 items
[P - 13:31:24] [Recycling Items] Recycled: ItemRazzBerry x 27
[P - 13:31:25] [Catch Pokemon] Found: 4 catchable Pokemon
[P - 13:31:26] [Catch Pokemon] Vulpix got away using a ItemPokeBall, status: CatchError
[P - 13:31:26] [Recycling Items] Recycled: ItemGreatBall x 39
[P - 13:31:26] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 13:31:27] [Recycling Items] Recycled: ItemPotion x 29
[P - 13:31:29] [Recycling Items] Recycled: ItemSuperPotion x 10
[P - 13:31:29] [UI] Updating...
[P - 13:31:30] [Catch Pokemon] Poliwag got away using a ItemPokeBall, status: CatchError
[P - 13:31:30] [Recycling Items] Recycled: ItemHyperPotion x 4
[P - 13:31:31] [Recycling Items] Recycled: ItemMaxPotion x 1
[P - 13:31:31] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 13:31:33] [Recycling Items] Recycled: ItemRevive x 18
[P - 13:31:33] [Catch Pokemon] Rattata got away using a ItemPokeBall, status: CatchError
[P - 13:31:37] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 13:31:37] [Catch Pokemon] Staryu got away using a ItemPokeBall, status: CatchError
[P - 13:31:39] [Recycling Items] There are no items to recycle

**Comment by curtiola** [comment]
Usually this means you're out of pokeballs, bot won't use great or ultra balls

**Comment by AkenoYukihime** [comment]
I have 90 pokeballs currently

**Comment by AkenoYukihime** [comment]
It seems to be working now for some reason thanks for replying

**Comment by curtiola** [comment]
If that's the number by the map it includes the great and ultra balls, to see individual numbers click the small switch on bottom left and check the left tab, if you do have pokeballs, maybe restart the program? Lol..

**Comment by curtiola** [comment]
Oh OK, awesome xP
