### ISSUE TITLE
iss API updated  ?? PokeBuddy 

### ISSUE THREAD

**Issue by RayTwente** [finndev/PokeBuddy#524]
PokeBuddy 

When go the API  updated ????

**Comment by curtiola** [comment]
Yes, it works

**Comment by curtiola** [comment]
Also, please close the issue so the devs don't have to, they have a lot of issues to go through already

**Comment by finndev** [comment]
@curtiola :+1:

**Comment by RayTwente** [comment]
14:41] [UI] Updating...
[P - 01:14:56] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc
[P - 01:15:20] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc
[P - 01:15:23] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc
[P - 01:15:39] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc
[P - 01:15:42] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc
[P - 01:15:43] Retrying request https://pgorelease.nianticlabs.com/plfe/153/rpc

**Comment by curtiola** [comment]
Server issues I assume, it seems lots of people are having problems

**Comment by RayTwente** [comment]
[P - 01:22:32] [Recycling Items] There are no items to recycle
[P - 01:22:51] Retrying request https://pgorelease.nianticlabs.com/plfe/412/rpc
[P - 01:22:55] [UI] Updating...
[P - 01:22:58] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 01:23:01] [Catch Pokemon] No Pokemon nearby
[P - 01:23:04] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 01:23:23] Retrying request https://pgorelease.nianticlabs.com/plfe/412/rpc
[P - 01:23:24] Retrying request https://pgorelease.nianticlabs.com/plfe/412/rpc
[P - 01:23:34] Retrying request https://pgorelease.nianticlabs.com/plfe/412/rpc
[P - 01:23:39] Retrying request https://pgorelease.nianticlabs.com/plfe/412/rpc

**Comment by curtiola** [comment]
Lol..... read my post?

**Comment by RayTwente** [comment]
Server issues api ????

**Comment by curtiola** [comment]
Nothing to do with api, servers are unstable/down

**Comment by RayTwente** [comment]
oke :)
