### ISSUE TITLE
No pokestops?

### ISSUE THREAD

**Issue by philippelabat** [finndev/PokeBuddy#534]
It's wierd, no pokestops are appearing on my map... Everything else is working fine.

Softban?

![screen shot 2016-08-08 at 7 00 45 pm](https://cloud.githubusercontent.com/assets/1538854/17499291/79af2a40-5d9a-11e6-8fb3-6bd1be9047ec.png)

**Comment by RoseCorpse** [comment]
Same for me, even with no bot.

**Comment by curtiola** [comment]
That screams server issues to me

**Comment by nothingtopick** [comment]
Pokemon go just updated might be that.
