### ISSUE TITLE
What's the best setting for farming XP?

### ISSUE THREAD

**Issue by HenghaoZhou** [finndev/PokeBuddy#536]
which place? walking speed?

**Comment by curtiola** [comment]
Sorry to be "that guy" but this is an issues forum, not a place for discussion, there is a thread for it currently #227
And high density areas like central park ny, Santa Monica pier LA, Sydney opera house, at whatever walking speed you desire

Please close this issue though, so the devs don't have to

**Comment by futi666** [comment]
i have sydney operahouse walkspeed 15, i make 50-70k xp in an hour
