### ISSUE TITLE
Anyone getting this Status: CatchError ?

### ISSUE THREAD

**Issue by HarounAns** [finndev/PokeBuddy#537]
![image](https://cloud.githubusercontent.com/assets/20847319/17500204/62d96f7c-5da1-11e6-91c8-75b24b897e57.png)

Anyone getting this error? I checked a couple of the previous issues but couldnt find one like this. If there is one can someone please redirect me.

**Comment by curtiola** [comment]
Usually this means you're out of regular pokeballs, it won't use great or ultra balls, the pokeballs number by the map includes great and ultra balls, to check the numbers individually you can click the switch on the bottom left corner to display the side tabs, items list is on the left

**Comment by HarounAns** [comment]
#525 Thank you
