### ISSUE TITLE
?? New Features ??

### ISSUE THREAD

**Issue by creeperkilla720** [finndev/PokeBuddy#538]
I know the devs are working hard but i just ant to know if anybody knows when the devs are gonna work on the update for pokebuddy which installs a bunch of new features which i have been hearing about

**Comment by curtiola** [comment]
Couldn't say, but I know finndev is no slacker, see #172 to check out some plans for the futur

**Comment by RayTwente** [comment]
I have a question maybe a stupid question
but ask him anyway
The opportunity is there for pokbuddy for windows phone

**Comment by curtiola** [comment]
That would be cool, I have never used a windows phone, don't know if it would work or not

**Comment by RayTwente** [comment]
okay :)
I do not know what but will be easy as ARM_Debug.appx can be made app for Windows Phone
