### ISSUE TITLE
?? Spots For Pokes ??

### ISSUE THREAD

**Issue by creeperkilla720** [finndev/PokeBuddy#539]
does anyone know where the best spot to catch pokemons are or where some nests are and one more thing lets say i go to a nest but the bot keeps farming pokestops and moves away from it will i still be able to catch a good amount of pokemon if i unchec1k farm pokestops, thank you whoever reads this

**Comment by curtiola** [comment]
Nests are good, if you uncheck farm stops the bot won't move, it's tough to micro manage the area you farm in, a lower walking speed is more likely to stay near the start point, like 2 or 3km per hour

**Comment by curtiola** [comment]
Also, the devs have a lot of issues to filter through, would you mind closing this one and the ones you open that have been solved? There is a general discussion thread: #227
