### ISSUE TITLE
using ultra ball to catch small cp pokemon

### ISSUE THREAD

**Issue by Aniruthan2495** [finndev/PokeBuddy#547]
[P - 08:17:05] [Catch Pokemon] We caught a NidoranFemale (Probability: 43.22%) with CP 239, used 1 x ItemUltraBall and received 210 XP
[P - 08:17:06] [Navigation] Walking from: 34.01046, -118.49498 to: 34.01077, -118.49542 with a distance of: 33 meters
[P - 08:17:08] Stopping...
[P - 08:17:11] [Farm Pokestops] Spinning Pokestop: 'S. M. U. R. R. F. Tree Tribute Mural'
[P - 08:17:12] [Farm Pokestops] Success -> Received XP: 50

**Comment by egimfun** [comment]
1. it used an ultraball because it was a low probability capture, the 40% you see is because the ultra ball increased it
2. why does it matter, if your in any major city you should be insanely overstocked on all pokeballs

**Comment by pokemonloverx333** [comment]
yes , and thhe program gets pokemon easier dont worry

**Comment by Aniruthan2495** [comment]
oh ok thanks then,got freaked that it uses ultrapoke ball

**Comment by lol998** [comment]
i tried it earlier and i think the problem is that its only using ultra balls to catch pokemon i tried earlier it caught 25 in a row only using ultraballs no matter the cp so i stopped it

**Comment by psblackz** [comment]
nope, now ultra ball always on low.. normal pokeballs were just fine..

**Comment by psblackz** [comment]
kinda sucks this

**Comment by lol998** [comment]
or is it cause i only have ultra and greatballs

**Comment by psblackz** [comment]
with pokeballs the bot  catch95% of them all

**Comment by GozarD** [comment]
I have normal pokeball, greatball and ultraball  .... and always use ultraball  :/

**Comment by Aniruthan2495** [comment]
0189, -118.49822 with a distance of: 52 meters
[P - 08:31:55] [Farm Pokestops] Spinning Pokestop: 'PF Chang's Art'
[P - 08:31:56] [Farm Pokestops] InventoryFull -> Received XP: 50
[P - 08:32:01] [Catch Pokemon] Found: 1 catchable Pokemon
[P - 08:32:03] [Catch Pokemon] We caught a Sandshrew (Probability: 100%) with CP 10, used 1 x ItemGreatBall and received 210 XP



i have normal pokeball too but why it is using great ball

**Comment by Aniruthan2495** [comment]
it must using balls in following order
ultraball
greatball
normal pokeball

**Comment by lol998** [comment]
now they just need to flip it

**Comment by Aniruthan2495** [comment]
yeah

**Comment by lol998** [comment]
hopefully wont take to long to fix that

**Comment by GozarD** [comment]
Features:
Use the best Pokeball  :/

**Comment by psblackz** [comment]
now i never have ultraball lol

**Comment by oOBlueArrowOo** [comment]
@psblackz me 2

**Comment by WilliamcaFox** [comment]
If you want to get your ultraballs back, just disable catching and let it farm. You aren't gonna be playing the game the same time the bot is running.

**Comment by finndev** [comment]
fixed
