### ISSUE TITLE
Keep using Berry even I have disable it in setting

### ISSUE THREAD

**Issue by agmster** [finndev/PokeBuddy#55]
Hi,

It keep using berry when catching pokemons even I have disabled it in the Setting page. I have even set the BerryProbability to 0 but it still keep using berrys. Anyone can help me on the setting?

I tried to download the latest zip and the issue still there.

Thanks

**Comment by wilbak** [comment]
go in to \\PokeBuddy-master\PokeBuddy and look for "setting" open that file and look through it for "UseBerries":true,"BerryProbability":"0.40" and make it false, this way it will be false on start up see if that make a difference

**Comment by agmster** [comment]
I have tried that before but it still using berries...

**Comment by wilbak** [comment]
might be an error in the script. watch and see if your berry count go's up or down?

**Comment by agmster** [comment]
it keeps going down, always 0 now..

**Comment by wilbak** [comment]
ss your setting file block out your login info

**Comment by GarfieldMao** [comment]
Same problem here. The bot keeps using berries even setting "UseBerries": false. And the "BerryProbability" doesn't work properly. The bot will still feed berries to a pokemon which the probability is larger than the value I set.

**Comment by agmster** [comment]
Here is my settings.json

```json
{
  "_berryProbability": "0",
  "_catchPokemons": true,
  "_evolveEggs": false,
  "_evolvePokemons": false,
  "_farmPokeStops": true,
  "_googleAccessToken": "",
  "_gpsAltitude": null,
  "_gpsLatitude": "22.293998",
  "_gpsLongitude": "114.168558",
  "_metersPerSecond": 7.0,
  "_recycleItems": false,
  "_rpcPassword": "pwd",
  "_rpcUsername": "email",
  "_isGoogleAccount": true,
  "_teleportMovement": false,
  "_throwAwayBadPokemons": false,
  "_useBerries": false,
  "RpcUsername": "email",
  "RpcPassword": "pwd",
  "GpsLatitude": "22.293998",
  "GpsLongitude": "114.168558",
  "GpsAltitude": null,
  "FarmPokeStops": true,
  "CatchPokemons": true,
  "EvolveEggs": false,
  "ThrowAwayBadPokemons": false,
  "TeleportMovement": false,
  "MetersPerSecond": 7.0,
  "UseBerries": false,
  "BerryProbability": "0",
  "GoogleAccessToken": "",
  "EvolvePokemons": false,
  "RecycleItems": false,
  "IsGoogleAccount": true
}
```

**Comment by Vanethir** [comment]
Solved with recent updates. Enjoy this feature. :)
