### ISSUE TITLE
Cant Catch Pokemon

### ISSUE THREAD

**Issue by AthosAbreu** [finndev/PokeBuddy#552]
After this updating of Pokebuddy , is not taking the Pokemons , Technique for harvesting the pokestops quietly , straight-laced pharma , only pokemon not!

**Comment by AthosAbreu** [comment]
before he took about 9 to 10 Pokemons every 2 minutes is now taking 1 or 2 at most when out who is spending the ultraballs

**Comment by finndev** [comment]
fixed

**Comment by AthosAbreu** [comment]
Thanks!!! great job
