### ISSUE TITLE
why the bot is using just ultraballs?

### ISSUE THREAD

**Issue by DGLVCY** [finndev/PokeBuddy#554]
????

**Comment by oOBlueArrowOo** [comment]
it uses the highest pokeball first

**Comment by finndev** [comment]
Hi, please try verion 0.0.7.6. I made a small mistake when reimplementing ball logic 

Should now work properly though

**Comment by DGLVCY** [comment]
hello... Tks, where can i find it?

**Comment by GozarD** [comment]
He wants to say you must to restart the app

**Comment by GozarD** [comment]
[P - 22:42:35] [Catch Pokemon] We caught a Pidgey (Probability: 30.56%) with CP 372, used 1 x ItemPokeBall and received 210 XP

NICE finndev ... you are the best :+1:
