### ISSUE TITLE
BOT IS USING ONLY ULTRABALL 

### ISSUE THREAD

**Issue by GozarD** [finndev/PokeBuddy#555]
Why bot is using only ultraball, maybe should be an option that we can choose if we want use a kind of ball

**Comment by IamDeric** [comment]
[P - 20:30:35] [Catch Pokemon] Catching a lured pokemon...
[P - 20:30:35] [Catch Pokemon] We caught a Tentacool (Probability: 45.14%) with CP 241, used 1 x **ItemGreatBall** and received 210 XP
[P - 20:30:35] [Navigation] Walking from: 37.80946, -122.41603 to: 37.80976, -122.41641 with a distance of: 29 meters
[P - 20:30:37] [Recycling Items] There are no items to recycle
[P - 20:30:39] [Transferring Pokemons] Transferring Pokemon away: Tentacool (CP: 130)!
[P - 20:30:39] [Farm Pokestops] Spinning Pokestop: 'USS Darter Propeller'
[P - 20:30:40] [Transferring Pokemons] Tentacool has been transferred
[P - 20:30:40] [Farm Pokestops] Success -> Received XP: 50
[P - 20:30:44] [Catch Pokemon] No Pokemon nearby
[P - 20:30:45] [Recycling Items] Recycling: 1 items
[P - 20:30:45] [Transferring Pokemons] Transferring Pokemon away: Tentacool (CP: 81)!
[P - 20:30:45] [Recycling Items] Recycled: ItemPokeBall x 3
[P - 20:30:45] [Transferring Pokemons] Tentacool has been transferred
[P - 20:30:45] [Navigation] Walking from: 37.80962, -122.41624 to: 37.80982, -122.41604 with a distance of: 18 meters
[P - 20:30:50] [Transferring Pokemons] Transferring Pokemon away: Tentacruel (CP: 266)!
[P - 20:30:51] [Transferring Pokemons] Tentacruel has been transferred
[P - 20:30:52] [Recycling Items] Recycling: 1 items
[P - 20:30:52] [Recycling Items] Recycled: ItemPokeBall x 3
[P - 20:30:52] [Farm Pokestops] Populated Pokestops
[P - 20:30:52] [Catch Pokemon] Catching a lured pokemon...
[P - 20:30:53] [Catch Pokemon] We caught a Poliwag (Probability: 35.29%) with CP 376, used 1 x **ItemPokeBall** and received 210 XP
[P - 20:30:53] [Navigation] Walking from: 37.80967, -122.4162 to: 37.80907, -122.41729 with a distance of: 72 meters


_it use all the pokeball. i just don't know what is the probability % to use a specific pokeballs._

**Comment by Thorben24** [comment]
Its okay imo. You get tons of ultraballs via pokestops. Ultraballs are also important for catching pokemons fast and reliable.  So why dont use ultraball all the time?

**Comment by LuzgGO** [comment]
Thorben24 I will need ultraballs while not using the bot and its hard to find

**Comment by curtiola** [comment]
It's fixed as pointed out by @IamDeric

**Comment by finndev** [comment]
fixed

**Comment by LuzgGO** [comment]
but the bot is now fixed, just updated it

**Comment by Thorben24** [comment]
Okay great. Anyway, if i need ultraball on mass i just activate farm pokestops and recycle items (Turn up Ultraballs to maximum and turn down the other usual stuff).
