### ISSUE TITLE
Ultraball usage

### ISSUE THREAD

**Issue by iRegal** [finndev/PokeBuddy#556]
After this new update, the bot always throw the best pokeball even for a low CP pokemon, is there anyway to configure this, maybe to use ultra/great ball on high CP/rare digimon only ?
and what is the recycle item filter does ? what's the numbers mean ?

**Comment by Dreker** [comment]
@iRegal  update!

**Comment by curtiola** [comment]
Fixed now, update again

**Comment by curtiola** [comment]
Numbers in item settings are the amount you will keep when recycling

**Comment by finndev** [comment]
fixed
