### ISSUE TITLE
Shuts down when exe is started

### ISSUE THREAD

**Issue by ragger10** [finndev/PokeBuddy#56]
Pokebuddy exe. just stops working and shuts programe down clicking on it. i have tried d/l new zip and tried on another com as well.. it just wont start. The zip needs to be fixed or someone needs to provide detailed info on how to go about on a fresh install.  Was working fine up until late last night. I have deleted and reinstalled a number of time.. No go.

**Comment by wilbak** [comment]
anti-virus might be stopping it. check your AV softwares for false positives

**Comment by brijei** [comment]
indeed av or troubleshoot compatibility
