### ISSUE TITLE
You have no pokeballs left

### ISSUE THREAD

**Issue by MrNightRyder** [finndev/PokeBuddy#57]
My wife who uses windows 7 gets "you have no pokeballs left" When I run her account on my pc/bot it works fine.  The only difference between our pc's is I am running windows 10 and she is running windows 7.  She is unwilling to move to Windows 10 so I'm wondering is this possibly a bug in Windows 7 for pokebuddy?

**Comment by wilbak** [comment]
go through your items and down size this was an easy fix cant get more pokeballs if you have no rom

**Comment by MrNightRyder** [comment]
We have done this and confirmed that we do in fact have plenty of pokeballs so that is not the issue.  Again, this only happens on my wife's pc it works fine on mine.  I'm spinning up a W10 virtual machine on hers to verify my suspicions.

**Comment by brijei** [comment]
run troubleshoot compatibility

**Comment by JustLegendHD** [comment]
im also having this issue, tried combatibility, troubleshooting and re downloading im on win10 btw

**Comment by Nyfaria** [comment]
i have 200 pokeballs, i rand troubleshoot compatibility, and am on windows 10.. i get this error.

**Comment by MrNightRyder** [comment]
Running it on a W10 virtual machine seems to be doing the trick.  Error is still happening on her windows 7 pro machine.  Perhaps maybe it's a windows patch of some sort?

**Comment by wilbak** [comment]
running as admin? on 7 and it might be that its pro try upgrading to ultimate also make sure she has all updates for win7 the error might be there aswell if all that is done and still error then its just not compatible

**Comment by MrNightRyder** [comment]
Running as admin did the trick good call willbak

**Comment by Nyfaria** [comment]
Well running it as Admin did not work for me..

**Comment by lordofthereef** [comment]
Was working fine for me last couple of days. Just logged in to another account (after already running the bot overnight on one account) and I get this error. I didn't even reload the app the first time, just hit stop and entered different credentials.
