### ISSUE TITLE
[Catch Pokemon] Encounter failed

### ISSUE THREAD

**Issue by Xalk444** [finndev/PokeBuddy#58]
![default](https://cloud.githubusercontent.com/assets/20630520/17270978/010318e6-5678-11e6-9347-6dc1f1e095b7.jpg)
Bothered to clean by hand

**Comment by efraim14** [comment]
encounter this problem also, have to transfer on my phone for those useless pokemon i don't want to.

**Comment by joaopedrosantos** [comment]
250/250 pokémons, you have to transfer some..
