### ISSUE TITLE
Repeated usage of single Pokestop. (InCooldownPeriod)

### ISSUE THREAD

**Issue by Vanethir** [finndev/PokeBuddy#6]
PokeBuddy keeps spinning same Pokestops multiple times. Does not happen with every Pokestop. 
Some people (e.g. @Kievtek) seem to be stuck at single Pokestop spinning the circle repeatedly.  

![incooldownperiod](https://cloud.githubusercontent.com/assets/20712566/17247907/db4fcb1c-5596-11e6-96e0-b5619cbeff4a.jpg)

**Comment by minecraftinventz** [comment]
That's to get the soft ban lifted. Leave it running 5-10 mins and it will work.

**Comment by Vanethir** [comment]
@minecraftinventz That's not a softban related problem. The message for a Soft Ban is **Success ->Received XP: 0**.

In this specific case it spins the Pokestop for multiple times. For the first spin you get the full 50 XP. Since niantic added a 5 minute Cooldown between additional spins it prints the message: **InCooldownPeriod -> Received XP: 0**

In my case there is no big difference in speed. Heard from 2 or 3 other people though who couldn't get forward because of this bug.

**Comment by Kievtek** [comment]
@Vanethir I have this every time,not is soft ban ..
