### ISSUE TITLE
SIMPLE FIX FOR THE BOT PROBLEM ATM!!!!

### ISSUE THREAD

**Issue by xXxCryxXx** [finndev/PokeBuddy#608]
Hello guys, 

I have the same problem like all of us! Just Delete the bot an reinstall tha PokeBuddy sometimes comes a Error Messege but you can ignore it.

Easy way to Fix this Problem ! JUST REINSTALL !!! DELET THE WHOLE FOLDER WHERE YOU BOT IS INSIDE!
AND INSTALL IT NEW!

**Comment by dannykyhung** [comment]
same result happened, didnt help

**Comment by xXxCryxXx** [comment]
What is your Problem with the Bot? Did he farm Pokemons or not? Or didnt catch pokestops?

**Comment by xXxCryxXx** [comment]
![github](https://cloud.githubusercontent.com/assets/20925692/17518002/54fb668a-5e46-11e6-8e96-b54fdab8affb.png)

It Works

**Comment by dannykyhung** [comment]
[P - 21:37:11] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 21:37:12] [Recycling Items] There are no items to recycle
[P - 21:37:15] [Navigation] Walking from: 22.29745, 114.1755 to: 22.29765, 114.1757 with a distance of: 19 meters
[P - 21:37:17] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 21:37:18] [Recycling Items] There are no items to recycle
[P - 21:37:21] [Navigation] Walking from: 22.29752, 114.17557 to: 22.29772, 114.17577 with a distance of: 19 meters
[P - 21:37:22] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 21:37:23] [Recycling Items] There are no items to recycle
[P - 21:37:27] [Navigation] Walking from: 22.29759, 114.17564 to: 22.29779, 114.17584 with a distance of: 19 meters
[P - 21:37:28] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...

It works fine for 5 minutes, and it happens again

**Comment by Nickya13** [comment]
My bot don't recycle my items

**Comment by xXxCryxXx** [comment]
Redowload the PokeBuddy a Update is out! 10 min ago Start it and let it load!

**Comment by dannykyhung** [comment]
didn't help i set it to 25km/h still, reload and update still not yet fixed

**Comment by xXxCryxXx** [comment]
Maybe the api is not Fixed you can also use Teleport Funktion it will take longer for egs
