### ISSUE TITLE
Recent Update Breaks PokeBuddy

### ISSUE THREAD

**Issue by WvuSoldier** [finndev/PokeBuddy#61]
The most recent update has caused the game to cash on startup on my Windows 10 machine. .Net Framework is up to date and AV and Firewall are down. If I block the update, older versions of the .exe load fine.

**Comment by Vanethir** [comment]
Any error message you get? 

If there are no error messages and it simply does not start try do move PokeBuddy.exe from the Loader directory to the upper directory and run it once again.

**Comment by WvuSoldier** [comment]
There were no error messages. Tried moving up a directory, no dice. Here is the relevant Windows Event Viewer message though! 
![image](https://cloud.githubusercontent.com/assets/20743772/17272671/8d3193d2-566a-11e6-9bf3-01989999b00e.png)[/image]

**Comment by WvuSoldier** [comment]
I was able to resolve this by simply downloading a new copy of the entire folder from github.
