### ISSUE TITLE
To Aazing

### ISSUE THREAD

**Issue by Avernicus** [finndev/PokeBuddy#627]
This is to amazing for my brain to handle.
Pokebuddy for Android?

**Comment by finndev** [comment]
this will not happen, sorry

**Comment by Avernicus** [comment]
Dont apologize, The dev should never need to apologize, unless a mistake is
made. As the consumer in this, I appreciate that I can use the bot. As a
developer, Im super intrigued. I write java plugins and mods for games. But
I dont know how to make desktop applications, nor do i know how to do
anything network related, so your the skilled one here. So thanks for
making something neat. The only unfortunate thing here is that once niantic
figures this out, the software is not really usefull. So thanks a Bunch!
Have a great day.
Jonathan
