### ISSUE TITLE
Getting Soft ban after using pokebuddy

### ISSUE THREAD

**Issue by sankystar** [finndev/PokeBuddy#63]
I got soft ban after using pokebuddy for while. I waited then again i was able to catch and do battle. I tried to verify if i will get banned again after using Pokebuddy. And yes i got banned again

**Comment by Nyfaria** [comment]
what do you mean by soft ban?

**Comment by sankystar** [comment]
I am not able to catch any pokemon, not able to do battles and now i logged out and not able to login again.

**Comment by Nyfaria** [comment]
Ok, so when you say you can't catch pokemon, do you mean they run away right away?

**Comment by sankystar** [comment]
yes, i throw a ball, and they ran away.

**Comment by Nyfaria** [comment]
Did you use pokebuddy in a far away place, than use it on your phone like right away?

**Comment by sankystar** [comment]
i was using santa monica as location and after 5-10 min i used pokemon go on my phone

**Comment by Nyfaria** [comment]
do you live within 5-10 mins of santa monica?

**Comment by sankystar** [comment]
nope, i am in India :P

**Comment by Nyfaria** [comment]
Well if you get banned. I will laugh. It keeps track of distance and time between.. either bot in a far away, or use your phone, dont do both.

**Comment by sankystar** [comment]
OKay. Its looked like my fault. But if i use far away location on popkebuddy to try then after how much time i should check out it on my phone?

**Comment by Nyfaria** [comment]
How much time does it take to get from Santa Monica to India? about that much time

**Comment by sankystar** [comment]
okay. Thanks
