### ISSUE TITLE
No way to forbid the bot to use Incubators

### ISSUE THREAD

**Issue by edgepp** [finndev/PokeBuddy#646]
Hello guys,

We can't deactivate the function of the bot to use Incubators.
If possible, we can just allow the bot to use the following Incubator (ItemIncubatorBasicUnlimited).

**Comment by pippo05** [comment]
+1

**Comment by p3monty** [comment]
and what eggs would be also nice

**Comment by pippo05** [comment]
use the 3 times incubator for 2km eggs is a tragedy!

**Comment by edgepp** [comment]
+1 ;)

**Comment by oOBlueArrowOo** [comment]
PLS SOMEONE HELP

**Comment by andry2895** [comment]
why ? the bot use incubator ?

**Comment by curtiola** [comment]
It's automatic, no way to stop it yet as far as I know, but I don't think it's a big deal, if you care about incubators it's probably your main account, and you probably shouldn't bot on your main account, get a fake account high level and wait for trading to be implemented instead xD

**Comment by andry2895** [comment]
you are sure the bot use incubator ? O_O i never see egg in incubation when login the accont

**Comment by curtiola** [comment]
Have you restarted recently? Bot got updated

**Comment by andry2895** [comment]
ooooh very nice then, i'm sorry !

**Comment by finndev** [comment]
Hi, the settings have been added. Please check the last version.

The appropriate settings are:

```
"UsePermanentIncubatorOnly": true,
"UseIncubators": true,
```

https://github.com/finndev/PokeBuddy/commit/ea5478b312cc6613d70e7c87f41a795e384a0e9b
