### ISSUE TITLE
PokeBuddy Problems with no spots or see any XP This you should do best

### ISSUE THREAD

**Issue by Ray-PoGo-NL** [finndev/PokeBuddy#652]
@@that's what I ge test and know that it works 100%
Follow this now and you're out of the problem :)
further're like an egg to hatch
continue to run 12 km-----do not go over 12 km dan,above 12 the egg is not hatched.
Niantic have admitted update adds
and also happens when your backpack is full of items
Niantic now see move in the difference
feather above the 65km or above you will often get thrown out and earn no xp 
then just put the bot at 12 or 25km walk *runs stably on
Niantic see the difference in velocity
![pokebuddy](https://cloud.githubusercontent.com/assets/20781652/17534556/05b88b22-5e8a-11e6-83b4-7e536f82f32f.png)

* ?Niantic on the update of (9-8-2016)
Added a dialog to remind Trainers that they should not play while traveling above a certain speed; - re-
Other fixes
Niantic now see move in the difference

![pokebuddy 2](https://cloud.githubusercontent.com/assets/20781652/17534591/2015caca-5e8a-11e6-82a6-910a86705b63.png)

*otherwise remove the buddy folder on your PC
and then download the new zip pokebuddy

**Comment by vendunk** [comment]
This is not true.

**Comment by Ray-PoGo-NL** [comment]
show me then @vendunk

**Comment by vendunk** [comment]
In a soft ban, Pokespots are still visible, you just get 0 xp from it. This issue is not a soft ban. Do you want to try running your configuration in multiple instances to try to replicate the issue before you try to suggest solutions to a problem you're not experienced with?

**Comment by curtiola** [comment]
Yeah the part where he mentioned soft ban was a warning, keep speed below 25 or something like that lol I admit it's hard to understand but don't be an ass
