### ISSUE TITLE
HOW THE FUDGE DO U STOP IT FROM USING INCUBATORSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

### ISSUE THREAD

**Issue by oOBlueArrowOo** [finndev/PokeBuddy#653]

**Comment by curtiola** [comment]
Click stop lol I don't think you can right now

**Comment by oOBlueArrowOo** [comment]
UGGGHHHHHHHHHHHHHH I WASTED 1 INCUBATOR LOL

**Comment by Ray-PoGo-NL** [comment]
I WASTED 1 INCUBATOR LOL

**Comment by R4NG3RR1K** [comment]
Same here, it buggs out for few minutes to then go back to farm again.

When incubator kicks in the bot bugs out.

**Comment by finndev** [comment]
Hi, the settings have been added. Please check the last version.

The appropriate settings are:

```
"UsePermanentIncubatorOnly": true,
"UseIncubators": true,
```

https://github.com/finndev/PokeBuddy/commit/ea5478b312cc6613d70e7c87f41a795e384a0e9b

**Comment by Ray-PoGo-NL** [comment]
settings have been added
