### ISSUE TITLE
Can not open Core/pokebuddy.Core.dll

### ISSUE THREAD

**Issue by Smmw** [finndev/PokeBuddy#665]
When I unzip the new version, the program told me that "Can not open Core/pokebuddy.Core.dll"
When I open pokebuddy.exe it says can not update. there is no poke stop and pokemons
![open](https://cloud.githubusercontent.com/assets/3632980/17536884/87b77b30-5eec-11e6-964b-8165f8103c8b.jpg)
![zip](https://cloud.githubusercontent.com/assets/3632980/17536885/87c98c26-5eec-11e6-8bc7-ddb5b7dcce00.jpg)

**Comment by hashkikker** [comment]
redownload

**Comment by curtiola** [comment]
It could be a firewall, but Access is denied usually means you have a permissions problem, make sure you're on an admin user account and that the parent folder allows write access (not read only) also you may need to add permissions in the security tab of the properties.

**Comment by curtiola** [comment]
Redownload will not work

**Comment by Smmw** [comment]
I have redownloaded many times. It shows the same error.

**Comment by curtiola** [comment]
Try run as admin, or try some of the things I mentioned above

**Comment by Smmw** [comment]
I rebooted the computer then it works...

**Comment by curtiola** [comment]
Nice, glad it did, surprised it was so simple, thanks for telling me how you did it
