### ISSUE TITLE
No Poke Balls

### ISSUE THREAD

**Issue by skomar1988** [finndev/PokeBuddy#67]
I log in and it says there are no pokeballs cant catch anything and it hits pokestops and still no pokeballs

**Comment by Vanethir** [comment]
#57 solved the problem. Try to run PokeBuddy as admin. If it doesn't work try the other options mentioned in this issue report. :)

**Comment by skomar1988** [comment]
how do I run as admin

**Comment by skomar1988** [comment]
Nevermind figured it out, but it still says I have no Items but inventory is full

**Comment by skomar1988** [comment]
[Screen shot.docx](https://github.com/finndev/PokeBuddy/files/392119/Screen.shot.docx)

**Comment by Vanethir** [comment]
Tried to turn it off and on again? Your inventory seems to be bugged.

**Comment by skomar1988** [comment]
yes I restarted the app, the computer, uninstall/reinstalled still same issue

**Comment by Cr4zZyBipBiip** [comment]
I confirm. I've the same bug....other bots drtect my inventory...not PokeBuddy
