### ISSUE TITLE
Nice places to farm!!!???

### ISSUE THREAD

**Issue by cadastro2005** [finndev/PokeBuddy#682]

**Comment by oOBlueArrowOo** [comment]
santa monica pier

**Comment by Thorben24** [comment]
@oOBlueArrowOo Damn awesome.

Got 40 pokemons in around 5 minutes: https://i.gyazo.com/fb6a4c7150e7a1d7f59fc0ceb0f48acd.png

@cadastro2005 Coordinates: 34.010139 , -118.496639

Thank you for sharing.

**Comment by cadastro2005** [comment]
@Thorben24  and @oOBlueArrowOo  thx

**Comment by legrestti** [comment]
Tokyo is very good too
