### ISSUE TITLE
no pokestops or pokemon

### ISSUE THREAD

**Issue by barbaricacidman** [finndev/PokeBuddy#695]
been botting for a few days now and all was working fine but now the bot cant find any stops or pokemon. i dont think its a bot issue i think its an account issue. when i log in to the account on my phone the stops/gyms/pokemon are missing on there.

**Comment by curtiola** [comment]
Could be server related too, I don't know for sure, but this happens on my phone every so often too

**Comment by barbaricacidman** [comment]
been happening since late last night (now 7:30am) im hoping its something simple like an issue on niantics end rather than a ban (dunno what a ban looks like)

**Comment by curtiola** [comment]
Even on the phone? A permaban would prevent you from logging in so you can be sure it's not that at least

**Comment by barbaricacidman** [comment]
yeah on phone i get the screen showing the map but no stops and no pokemon, there is normally a stop and a gym close by me

**Comment by jayhao2000** [comment]
Niantic is doing something...

**Comment by barbaricacidman** [comment]
i just transfered a load of pidgeys and evolved one and its all come back

**Comment by curtiola** [comment]
Glad it works, mind closing the issue? The devs have a lot of them to filter through

**Comment by barbaricacidman** [comment]
how do i close? feel stupid now, i see its open(green box)

**Comment by curtiola** [comment]
Ty :)

**Comment by yoyog** [comment]
This issue happened to me. Did you jailbreak your phone cause sometimes the jailbreak messes with location services there's lot of info on it I recommend you check it out if this happens again. That causes no gps causing nothing to show up.
