### ISSUE TITLE
No items, level, or pokemon

### ISSUE THREAD

**Issue by ipwns** [finndev/PokeBuddy#7]
When the app loads I have no level, experience, or items. The only thing it shows that I have is stardust. 
![image](https://cloud.githubusercontent.com/assets/20726310/17252051/b6fd1d9e-5570-11e6-8b2b-65a66418d513.png)

**Comment by Bayramklc** [comment]
update pokebuddy or restart

**Comment by vorasaurus** [comment]
I'm having the same issue =\. (Just downloaded the latest version that was updated 6 hours ago, restarted multiple times.. still no items being shown in the inventory.)

**Comment by ipwns** [comment]
I fixed it by running troubleshoot compatibility.
