### ISSUE TITLE
Error in log : System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by Tchingy** [finndev/PokeBuddy#70]
Hi, got this error in Log; program still functionning after that. Just to let you know

> [P - 00:00:43] [Catch Pokemon - ERROR]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at 0o<\&p!iPZ qLTocDBI\,F\*/3\[-.iq_=k"2\,\]t?#\[8Pi\,FIz#^\.O"`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at 0o<\&p!iPZ qLTocDBI\,F\*/3\[-.9jz;q@'?GB;tF~p"ci@?dU-h2`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at  PiN;f6le3/5c"!U 7:vS#|O%._$X;AH}n-xbg{ndO9%uu1^ t$.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at PokeBuddy.Niantic.Behaviours.CatchPokemons.<Execute>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

**Comment by Vanethir** [comment]
Should be solved with recent updates. If there are still problems notice us, please. :)
