### ISSUE TITLE
There appears no pokestop.

### ISSUE THREAD

**Issue by mayconvds** [finndev/PokeBuddy#703]
I closed the pokebuddy, now is not showing anything around me.
Can someone help me?

**Comment by Deuxgod** [comment]
Restart your router to change IP. If that doesn't work, set a VPN and connect through it. You're probably IP banned for some time.

**Comment by mayconvds** [comment]
Solved

**Comment by KT2163** [comment]
Please tell how u solved the issue. I have Same problem.

**Comment by mayconvds** [comment]
In fact the problem returns again, I suspect it's because of Pokebuddy server, you are leaving our prey accounts.
