### ISSUE TITLE
am i banned?

### ISSUE THREAD

**Issue by 2stronkkk** [finndev/PokeBuddy#709]
i have no pokestops, no gyms, no pokemons..nothing. am i perma banned?

**Comment by Thorben24** [comment]
No, your ip adress is banned. Change your IP adress by restarting / relogging your router (95% of the cases you have a dynamic ip adress) and the problem is fixed. For the future, you can not run more than 1 pokebuddy with the same ip at the same time.

**Comment by ukyo28** [comment]
So if we use only 1 pokebuddy, we will not encounter IP ban?

**Comment by 2stronkkk** [comment]
i only use one account and never go away from san francisco. its weird

**Comment by Thorben24** [comment]
@ukyo28 
Since my ip ban the last night I setted up 2 proxy servers. So i have now each PokeBuddy instance / each account an own ip adress. Since 6 hours i got not a single problem anymore.

@2stronkkk 
Well thats weird. Are you sure that you are the only one botting / playing in your network?

**Comment by 2stronkkk** [comment]
yes i am. i already restart my router and cant play again. damn

**Comment by dzdam** [comment]
i think it has to do with the new release...however proxy is a good idea

**Comment by 2stronkkk** [comment]
can some1 explain how i do that "proxy"?

**Comment by Thorben24** [comment]
To be honest i dont know a good way to do this free. I highly prefer to setup your own proxy servers with an own linux vps with 2 or more ip adresses (as much pokebuddys you wanna run at the same time as much ip adresses you will need) for around 10 usd / month @ vultr

You can google then: Setup proxy linux debian or something and you should find how you can do this. Its not that way difficult if you are using more than 1 hour per week your computer. 

After that you will need the software Proxifier, there you can add all your proxy servers and give every PokeBuddy.exe you are running his own Proxy Tunnel.

**Comment by 2stronkkk** [comment]
but what the point of proxy? just hide ur ip and change it?

**Comment by Thorben24** [comment]
A proxy will give you a new ip adress. The whole traffic is send to the proxy server, and the proxy server send it to the reciver, for example the pokemon go servers.

Its in this case just to "Hide" your ip. You change your ip adress usually by restarting / relogging your router, cause 95% of all providers running dynamic ip adresses.
