### ISSUE TITLE
There are no pokestops nearby(not clone of #68)

### ISSUE THREAD

**Issue by SirFritzRCS** [finndev/PokeBuddy#71]
Whenever I start, no matter where in the world I set it, I constantly get problems with all the pokestops disappearing, even though I know almost exactly where most of them are. Any idea why, or solutions? Been happening for 2 days now..

**Comment by darkendvoid** [comment]
I had this happen to me as well. Appears to be a movement based softban, I had to "walk" my character about 1km before pokestops and such loaded.

**Comment by Vanethir** [comment]
Should be a Niantic Server related problem. It's an issue about location oriented information. Tried to login into different accounts and there aren't Pokestops either.. 
Didn't try to login in Nox though. Once I notice the problem again I will try it as well and will inform you here for 100% certitude.

**Comment by Templarum** [comment]
Was having the same problem, solved by moving on a less populated farm spot, where they're not a lot of people using the app, like a small town, so, it seems the problem is Niantic Side (Sorry for Bad English, hope you'll be able to understand)
