### ISSUE TITLE
Is it working for anyone?

### ISSUE THREAD

**Issue by JewBagel** [finndev/PokeBuddy#715]
Ive tried about everything

**Comment by ukyo28** [comment]
Working

**Comment by novoselovd** [comment]
For me it works for like 5 mins and stops

**Comment by JewBagel** [comment]
no problems at all ? are you using a vpn and did you just start using it today?

**Comment by Thorben24** [comment]
As you know, everything working. Just dont use more than 1 PokeBuddy/Account each ip adress.

**Comment by JewBagel** [comment]
lmao man ive told you like twice already ive never used more than 1 pokebuddy never needed too doesnt seem to help my case tho

**Comment by Thorben24** [comment]
I also told you multiple times to change your ip adress, best and fast way by relog/restart your router is fixing your problem.

**Comment by ukyo28** [comment]
@Thorben24 

It's okay to use the Incubator settings right?

**Comment by JewBagel** [comment]
i tried reseting my router already going to try for longer this time sorry if im angering you and thank you for being patient with me

**Comment by Thorben24** [comment]
@ukyo28 
I use it all the time. But many guys have have a better experience without using the Incubator feature, so if everything is fine for you, you can use it imo.

**Comment by Thorben24** [comment]
@JewBagel 
www.utrace.com - Save your ip adress and have a look on it after you restarted your router. Then you can be 100% sure that your ip is renewed.

**Comment by JewBagel** [comment]
restarted my router nothing changed sadly

**Comment by JewBagel** [comment]
that site doesn't exist

**Comment by Thorben24** [comment]
Sorry, its: http://www.utrace.de/

**Comment by JewBagel** [comment]
its fine man i got it working on vpn my service provider is very strict i highly doubt they would allow an ip change just by restarting of the router

**Comment by JewBagel** [comment]
im guessing the first few vpn servers i choose were already banned that may be why i got it working
