### ISSUE TITLE
Pokemon go on iPad can't use google account sign in?

### ISSUE THREAD

**Issue by kenwang911** [finndev/PokeBuddy#718]
Hi all. As title iPad Pokemon go sign in selection only have PTC sign in, no google account ?

**Comment by Thorben24** [comment]
I just got an iPad Mini, but i can choose between PTC or Google.

**Comment by kenwang911** [comment]
@Thorben24 have you put a SIM card in your iPad mini?

**Comment by Thorben24** [comment]
@kenwang911 No, I only used it sometimes at home and 1 time outside (i gave myself wlan via hotspot on iphone).

**Comment by kenwang911** [comment]
![image](https://cloud.githubusercontent.com/assets/20893316/17550235/2939a388-5f48-11e6-8373-ab256c43a448.png)

**Comment by kenwang911** [comment]
Wifi connect. No selection for Google account

**Comment by 404unknown** [comment]
Why you ask this here? Your question/issue is completely irrelevant to Pokebuddy. Ask this somewhere else, dont make this spammy forum even more spammy with hundreds of off-topic posts, duplicate posts. It will not help the developer improve pokebuddy as all the constructive and feature ideas post sink into the seas of complains, "NOT WORKING" posts,and off-topic posts like yours. Sorry if I sound salty, but seeing those 468 issues really frustrate me

**Comment by Thorben24** [comment]
Never seen that before. And y somehow 404 is right, you should ask this somewhere else. The devs have to take a look into the issues.

**Comment by kenwang911** [comment]
Topic closed.
