### ISSUE TITLE
Pokebuddy now only catches the most common pokemon

### ISSUE THREAD

**Issue by vicrya** [finndev/PokeBuddy#735]
unlike before, it seems the bot only catches pidgey, zubat, oddish these kinds of pokemon now. is it only me?

**Comment by AHNMA** [comment]
Catched in last 15 Min: Magnemite, Venonat, Venomoth, Meowth, Abra... so i dont think its related to the bot.

**Comment by Thorben24** [comment]
I got no problems with catching pokemons.

**Comment by KT2163** [comment]
I live in Hong Kong. Let me know if you wanna try.
