### ISSUE TITLE
Appologies if this has already been mentioned

### ISSUE THREAD

**Issue by brynnie1** [finndev/PokeBuddy#740]
i have the pokebot working - and it goes to the pokestop but don't get anything from it - just XP is that because i have a temp ban or is that possibly because my inventory is full? 
any help would be appreciated

**Comment by Thorben24** [comment]
If you get just XP your inventory is full. What is the item statistic telling you? (You have to activate the stats  by clicking the button in the left-botton.

**Comment by brynnie1** [comment]
it says items 189/350 and still going to pokestops and not collecting anything just xp

**Comment by Thorben24** [comment]
Oh I see, since the last PokeBuddy update it dont show you which items you get anymore. So its for everyone, not just you. You still get the items.

**Comment by brynnie1** [comment]
oh thats ok got worried for a moment thinking maybe i had a temp band thanks for commenting
