### ISSUE TITLE
transfer pokemons help!!

### ISSUE THREAD

**Issue by sacronor** [finndev/PokeBuddy#741]
Hi guys!
Is there a way to keep just 1 pokemon of each? 
Bot saves all pokemon above cp1000. That dont work for me, i wanna just 1 with the higher cp ofcorse  :(

**Comment by perfidiousdan** [comment]
It a mess dont use it

**Comment by sacronor** [comment]
what u mean?

**Comment by Thorben24** [comment]
By activating transfer bad pokemon it will keep everytime 1 pokemon of each with the highest CP. The Settings and generally is buggy and will be fixed with the next upcoming patches.
