### ISSUE TITLE
LOGIN FAILED

### ISSUE THREAD

**Issue by knight16** [finndev/PokeBuddy#75]
![image](https://cloud.githubusercontent.com/assets/20701626/17275934/54b2e360-5743-11e6-8192-4d4d88b5e90d.png)

**Comment by knight16** [comment]
thanks ... but it still "LOGIN FAILED" :(

**Comment by dome970** [comment]
Well :D then u have to wait for a responds from the Coder himself :D

**Comment by knight16** [comment]
i hope so :(

**Comment by finndev** [comment]
Sync your PC's time

**Comment by shiink** [comment]
i'm also have this problem :'(

**Comment by Vanethir** [comment]
Check #49.

Probably empty spaces, wrong datetime of your pc clock or old version you are running.
