### ISSUE TITLE
Revert To Previous Bot

### ISSUE THREAD

**Issue by SomeLameDude** [finndev/PokeBuddy#759]
I have had a bot running for 2 days solid.  It is or was the version before the incubator was added and it was working fine this morning but the inventory was full this morning so I had to stop it which of course it update to the new bot which only works for a few minutes before it stops farming and gets ip banned.  Is it possible to revert to the previous working bot?

**Comment by novoselovd** [comment]
Same here :(

**Comment by Skolzack** [comment]
Oh god, I'm happy to not closed my Pokebuddy. I'll keep him opened xD

**Comment by SomeLameDude** [comment]
I never closed mine either but I did stop it.  As long as it can keep recycling and transferring stuff, I wouldn't touch it.

**Comment by Skolzack** [comment]
So Niantic patched Pokebuddy and are banning everyone. lul

**Comment by SomeLameDude** [comment]
I honestly don't think it is Niantic or the old bot that I had running would have been ip banned too right?  I think something in the new version is triggering the soft bans from Niantic but that is just a guess on my part.  I would love to see the old bot thrown back up and let us give it a try.

**Comment by Skolzack** [comment]
@SomeLameDude I am using the new version with Incubators and all works fine. But I didnt closed my Pokebuddy since yesterday after the new update.

**Comment by SomeLameDude** [comment]
how long has it been running.  mine ran for about 10 minutes like that before crapping out

**Comment by finndev** [comment]
https://github.com/finndev/PokeBuddy/commit/771cdd4438e244751c66527ebad5ed6289528279

should fix all those mentioned issues
