### ISSUE TITLE
Bot not excuting accordingly

### ISSUE THREAD

**Issue by RaymondKooZhunWui** [finndev/PokeBuddy#761]
After I have set the setting everything accordingly, below is the log i got and its still freeze at the same row. Please advise.

[P - 00:45:18] --------------------------------
[P - 00:47:43] Attempting to Login...
[P - 00:47:43] Logging in with method: PTC as Auth Provider
[P - 00:52:57] Stopping...
[P - 00:53:30] Attempting to Login...
[P - 00:53:30] Logging in with method: PTC as Auth Provider

**Comment by TeemoOnShrooms** [comment]
Try to log with google account if possible

**Comment by RaymondKooZhunWui** [comment]
I did, and I have tried with multiple gmail account too.

**Comment by Skolzack** [comment]
@RaymondKooZhunWui Do you have 2 steps verification on gmail account? If yes, disable it and try again.

**Comment by RaymondKooZhunWui** [comment]
thanks everyone, the issue has been solved
