### ISSUE TITLE
its says FAILED TO GET UPDATEDATA, GITHUB MY BE DOWN HELP PLS

### ISSUE THREAD

**Issue by edgardp88** [finndev/PokeBuddy#795]
EVER SINCE I GOT IT IT HAS BEEN SAYING THIS... pls help

**Comment by curtiola** [comment]
Antivirus or windows firewall could be blocking the connection

**Comment by curtiola** [comment]
If not, maybe permissions, make sure you're on an admin user account and try run as admin

**Comment by edgardp88** [comment]
alright ill try that right now! ill tell u if it works!

**Comment by chopperaus** [comment]
Have had a couple of times but still loads when u ok out and cycle to login. In saying that have closed and tried again and has updated

**Comment by edgardp88** [comment]
Its works now thanks!! and keep up the good shit on this!

**Comment by curtiola** [comment]
Awesome, was it an Antivirus?
