### ISSUE TITLE
No pokestops nearby 

### ISSUE THREAD

**Issue by k2sapex** [finndev/PokeBuddy#80]
The map detect me the pokestops, the bot takes someone but when 5 minutes elapse that message "No pokestops nearby" shows all the times and in the map dont show any pokestop fix it pls!

**Comment by finndev** [comment]
try last version

**Comment by k2sapex** [comment]
Now its found correctly thanks!

**Comment by jackson55778167** [comment]
hey , how would you solve the issue?i am having the same problem now...no pokestops nearby thanku
