### ISSUE TITLE
I See Pokestops and get XP from them, but no items. Also I don't attempt to capture pokemon

### ISSUE THREAD

**Issue by Padawin86** [finndev/PokeBuddy#800]
I've seen a lot of people commenting about IP Ban or Soft ban, but I don't think that's my issue. I see pokestops and can spin them and get 50 XP, but they don't give me any items. It also sees catchable pokemon but the bot doesn't attempt to catch them. I'm also not seeing my trainer level or pokemon and items like I used to. I've re-downloaded the bot but same issue. Here are some sample logs: 

**[P - 19:07:52] [Farm Pokestops] Spinning Pokestop: 'Nearby Farm'
[P - 19:07:53] [Farm Pokestops] Success -> Received XP: 50
[P - 19:07:57] [Navigation] Walking from: 38.XXXXX, -77.YYYYY to: 38.XXXXX, -77.YYYYY with a distance of: 233 meters
[P - 19:08:03] [Catch Pokemon] Found: 3 catchable Pokemon
[P - 19:08:44] [Farm Pokestops] Spinning Pokestop: 'Trolls at Nearby Farms'
[P - 19:08:45] [Farm Pokestops] Success -> Received XP: 50
[P - 19:08:49] [Farm Pokestops] Populated Pokestops
[P - 19:08:49] [Navigation] Walking from: 38.XXXXX, -77.YYYYY to: 38.XXXXX, -77.YYYYY with a distance of: 39 meters
[P - 19:08:54] [Farm Pokestops] Spinning Pokestop: 'Nearby Farm Bees'
[P - 19:08:54] [Farm Pokestops] Success -> Received XP: 50
[P - 19:08:58] [Navigation] Walking from: 38.XXXXX, -77.YYYYY to: 38.XXXXX, -77.YYYYY with a distance of: 40 meters
[P - 19:09:00] Stopping...**

Update: After opening the game and examining the logs, I am getting items from the pokestops but they are not being logged by PokeBuddy. The bot is also not catching pokemon

**Comment by curtiola** [comment]
Sometimes a full inventory will do this, you have your item recycle settings set up? Also only have 1 of the egg incubator options chosen?

**Comment by Padawin86** [comment]
Sorry, forgot to put my settings.

Farm Pokestops is enabled
Catch Pokemon is enabled
Recycle Items is enabled
Inventory is close to full, but not full

I do have both of the Incubator options selected so I'll try only the permanent incubator option

**Comment by Padawin86** [comment]
Same results

**Comment by Padawin86** [comment]
Ok, so I ran it again and started seeing "Inventory Full" in addition to the "Received XP: 50" so I opened up the game and checked the logs and it would appear I am getting items. However it is still not catching the pokemon.

**Comment by curtiola** [comment]
Weird, have you tried disabling catch pokemon and re-enabling it or restarted the program?

**Comment by Padawin86** [comment]
Yes to both. When you run the bot do you see your trainers level and your pokemon?

**Comment by curtiola** [comment]
Yeah you don't?  I know of 4/5 cases with that problem that solved it by restarting the pc xD

**Comment by Padawin86** [comment]
Yup. Troubleshooting 101. Restarting fixed it. 

Never thought I'd be so happy to catch a Pidgey

**Comment by curtiola** [comment]
Hahaha nice, glad it worked
