### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Mpako6ec** [finndev/PokeBuddy#822]
Bot is down?

[P - 10:59:42] [Recycling Items] There are no items to recycle
[P - 10:59:43] [Catch Pokemon] No Pokemon nearby
[P - 10:59:43] [Navigation] Walking from: 40.78509, -73.96828 to: 40.78529, -73.96808 with a distance of: 17 meters
[P - 10:59:46] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 10:59:47] [Recycling Items] There are no items to recycle
[P - 10:59:50] [Navigation] Walking from: 40.78511, -73.96826 to: 40.78531, -73.96806 with a distance of: 17 meters
[P - 10:59:51] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 10:59:52] [Recycling Items] There are no items to recycle
[P - 10:59:57] [Navigation] Walking from: 40.78516, -73.96821 to: 40.78536, -73.96801 with a distance of: 17 meters
[P - 10:59:57] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 10:59:58] [Recycling Items] There are no items to recycle
[P - 11:00:03] [Navigation] Walking from: 40.78518, -73.96819 to: 40.78538, -73.96799 with a distance of: 17 meters
[P - 11:00:04] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 11:00:04] [Recycling Items] There are no items to recycle
[P - 11:00:05] [Catch Pokemon] No Pokemon nearby
[P - 11:00:09] [Navigation] Walking from: 40.7852, -73.96817 to: 40.7854, -73.96797 with a distance of: 17 meters
[P - 11:00:09] [Recycling Items] There are no items to recycle
[P - 11:00:11] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 11:00:15] [Navigation] Walking from: 40.78523, -73.96815 to: 40.78543, -73.96795 with a distance of: 17 meters
[P - 11:00:15] [Recycling Items] There are no items to recycle
[P - 11:00:17] [Transferring Pokemons] No Pokemons available for transfer. Trying again later...
[P - 11:00:21] [Recycling Items] There are no items to recycle
[P - 11:00:21] [Navigation] Walking from: 40.78525, -73.96813 to: 40.78545, -73.96793 with a distance of: 17 meters

**Comment by DatFIXER** [comment]
#771
