### ISSUE TITLE
Pokemon Go Errors

### ISSUE THREAD

**Issue by Isheunopa** [finndev/PokeBuddy#83]
after using pokebuddy i thought i would go out to a gym and battle, but everytime i tried to battle it gave me an error message, i sign out and signed back in and it still didnt work to i went to a pokestop and the pokestop didnt work either and i cant catch pokemon. so im wondering if there i have to wait a few hours after using pokebuddy to use pokemon go because i cant do anything at the moment on the app

**Comment by Vanethir** [comment]
If you travel a huge distance in short time you get "Soft banned". Either wait for a few hours before using it at 2 different locations or wait for the Soft Ban to end afterwards.
Soft Ban should end within 3-4 hours max. If you don't want to wait you should be able to end the soft ban by spinning a Pokestop up to 50 times or run a tool doing that for you. (Didn't try the manual solution myself though.)

**Comment by Isheunopa** [comment]
Thank you for the help my pokemon go is working fine now.

**Comment by paulpetone** [comment]
# Pokebuddy stopped working for me, i guess that is because the new pop up that appears when players do the login. I didn't went to so far to take a "Soft banned".
