### ISSUE TITLE
Sugestion - Invidual Values (IV)

### ISSUE THREAD

**Issue by raulfdm** [finndev/PokeBuddy#838]
Hello guys.

Today I found this site (https://pokeassistant.com/main/ivcalculator). There, they explain about what is IV and how to calculate:

> Each type of Pokemon has a base set of attributes for Stamina, Attack and Defence. Each specific Pokemon is "born" with it's own IV (individual values), that further increase these stats by 0-15 extra points. You can not change the IV's, not all Pokemon are born equal.
These IV's make small differences in the final power of a Pokemon. For example, the base attributes of a Charizard are 212, 182, 156. This would be the "worst" charizard available where all IV's are zero. With max IV's, a Charizard would have 227, 197, 171. Each of these Atk, Def and Stam values for Charizard are only 7-10% better.
Nonetheless, if having the absolute best Pokemon is critical to you, this tool wll help you find the hidden IV values that your Pokemon has so you can decide to keep it or try for something better.
This tool uses the two following formulas and the inputs you provide about your Pokemon to attempt to identify its IVs:
HP = (Base Stam + Stam IV) * Lvl(CPScalar)
CP = (Base Atk + Atk IV) * (Base Def + Def IV)^0.5 * (Base Stam + Stam IV)^0.5 * Lvl(CPScalar)^2 / 10
Note that Pokemon have hidden levels and each level requires two "Power-Ups", this tool will display Level 4.5 if your Pokemon has had one Power-Up after level 4.
Major credit to u/__isitin__ for digging up the data.
Huge thanks to trainer JarydC for getting the javascript for this across the line at the 11th hour, and to Ciuff and Nylonee for getting the ball rolling.

Than, I thought about implement this in a future feature. We'll know about how pokemon we need to stay ou transfer.

I'm developer, but I don't know about this program language. By the way, I think that is a good idea!

**Comment by r0nalxd** [comment]
Has already been mentioned in #172
