### ISSUE TITLE
IP Banning Information ***

### ISSUE THREAD

**Issue by Shmurfs** [finndev/PokeBuddy#839]
I made a post yesterday about the bot only going to maybe 10 pokestops and then getting stuck/ not working spamming the "[Navigation] Walking from: " command, I found out this morning that this only seems to happen in certain parts of the world. It was happening to me in San Francisco, Pier 39, I moved to Hong Kong and the bot works fine. (Yes I made sure I wasn't soft banned/IP banned when I was moving around). Just wanted to give some info I found strange, maybe it could help. (If there's somewhere I could post info please let me know I know the issue page isn't for this.)

**Comment by catch3mAll** [comment]
I can second that. IP ban seems to be worse at Pier 39.
