### ISSUE TITLE
Always catch flee for few mins, anyone can help?

### ISSUE THREAD

**Issue by anderchunk** [finndev/PokeBuddy#848]

**Comment by tsingjun** [comment]
That's because you transfer so far away from the last place you're farming.
Just waiting for minutes after place change.

**Comment by anderchunk** [comment]
thanks buddy, normally how long do we have to wait from one place to transfer to another place?

**Comment by tsingjun** [comment]
I don't know that either. So ask the GM of the Pokemon Go? :smile:

**Comment by anderchunk** [comment]
LOL, thanks buddy
