### ISSUE TITLE
fixed ip block ... your blocks are just driver block

### ISSUE THREAD

**Issue by hendroxy** [finndev/PokeBuddy#858]
since last update they added driver etc..
Trainers must confirm they are not driving in order to continue playing.

if you use slow speed like 2-3 kmh all is fine
and use only one client of pokebuddy

i hope it helps

**Comment by Kaczarouski** [comment]
I will try this!

**Comment by Kaczarouski** [comment]
Works for me on a speeds of 4km/h

**Comment by r0nalxd** [comment]
That might be the other problem besides the IP ban! My speed is 5km/h no problems @ that speed either

**Comment by BendingUnitBender** [comment]
Kinda ridiculous considering that I've seen kids on scooters and bicycles while catching pokemons. Some of them are even pretty smart and put a cell phone mount on their bikes. They do this to hatch eggs and now they will be punished if deemed too fast.

**Comment by cykablyater** [comment]
so you dont get ip banned when you set the speed below 5 km/h ?

**Comment by hendroxy** [comment]
for me it was the solution: low speed and just one client.

but a friend of  mine run with 40 km/h in same country for  more then 8 hours with only one client  and all fine for him.

**Comment by mpdt1234** [comment]
I use 8 Km/Hr and have had an issue since adjusting my VPN settings.
