### ISSUE TITLE
Is it just me, less pokemon catch?

### ISSUE THREAD

**Issue by lilililo920** [finndev/PokeBuddy#885]
Lately, pokebuddy only catch max 1 pokemon at 1 minutes. I try different location with lots of pokestop still no luck.

**Comment by RoseCorpse** [comment]
same for me

**Comment by shiitan5** [comment]
you guys are lucky that the bot is working lol

**Comment by Anatine** [comment]
That's why I was trying to run it with just Pokemon catching and not Poke stops.

**Comment by lilililo920** [comment]
ok then, i usually can catch 2 at least in a minutes, so 1 hour botting give me around 120 pokemon.

this stil great tools, am just wondering.
