### ISSUE TITLE
[Error] Please verify your account

### ISSUE THREAD

**Issue by zimbawezaw** [finndev/PokeBuddy#92]
This keeps happening every time i try to login

[Error] Please verify your account

**Comment by Vanethir** [comment]
Do you use a PTC account? They sent an email for account activation.

**Comment by zimbawezaw** [comment]
I already activated but idk why it keeps happening

**Comment by zimbawezaw** [comment]
is there an updated version?

**Comment by Vanethir** [comment]
There should be about 6 updates within the last 2hours. Last one was ~25 minutes ago. 
Probably updating will solve your problem.

**Comment by zimbawezaw** [comment]
where can i find the updates?

**Comment by Vanethir** [comment]
Usually restarting the PokeBuddy.exe should start the Launcher and update it. If it doesn't work for you try to download the new version from [here](https://github.com/finndev/PokeBuddy/archive/master.zip) manually and reinstall the application.
