### ISSUE TITLE
[Farm Pokestops] OutOfRange -> Received XP: 0 pokestops error

### ISSUE THREAD

**Issue by BigG1** [finndev/PokeBuddy#946]
It's catching pokemons but have some issues today for the first time with pokestops. It says:

[Farm Pokestops] OutOfRange -> Received XP: 0  

 for any pkestop, the same..

**Comment by adrianmdm** [comment]
softban o ipban?

**Comment by BigG1** [comment]
Don't know how to recognize them 😂
