### ISSUE TITLE
Failed to open PokeBody.exe

### ISSUE THREAD

**Issue by Smmw** [finndev/PokeBuddy#95]
I down loaded the PokeBuddy-master, extract the PokeBuddy.zip and overwrite the files then open PokeBuddy.exe then it seems that it is trying to open the PokeBuddy then it disappeared after 2 seconds  i have tried many times. please help. I am using W10

**Comment by Lvnee** [comment]
This bug I had download the PokeBuddy simply re on GitHub then had to go back

**Comment by Vanethir** [comment]
Try to move the PokeBuddy.exe to the parent directory and run it from there. Should solve the problem.

**Comment by brijei** [comment]
download the latest master version of pokebuddy.
extract pokebuddy.zip and extract it in the master folder. click yes to replace all the files. this should fix your problem. if it doesn't run troubleshoot compatibility.

**Comment by Smmw** [comment]
I have tried run it as troubleshoot compatibility as W7 and W8 it did not work

**Comment by brijei** [comment]
and the clean new download? Master and extract inside the master?

**Comment by Smmw** [comment]
Yes I did exactly what you told me。

**Comment by brijei** [comment]
then I don't have a answer to your problem at this moment. if you want I can take a look for you with team viewer. send me an email bencgeerdsproductions@gmail.com or a hangout message bencgeerds@gmail.com or telegram @YourDestination

**Comment by brijei** [comment]
please report it if it works at the pc of your roommate. so this ticket can be closed.

**Comment by Smmw** [comment]
It works on my room mate`s computer, He is got a W8 system. but I got the erroe that please verify you account...that confuse me........

**Comment by brijei** [comment]
that error is a common error from Google itself. wait a few minutes and try again.

**Comment by Smmw** [comment]
it works on my room mate`s computer thanks!!

**Comment by brijei** [comment]
Your Welcome

**Comment by Smmw** [comment]
may i know the location in the app?

**Comment by brijei** [comment]
location?

**Comment by Smmw** [comment]
No worry..I used the google to check the location, I reboot my computer and it works ....... Oh My God!!!

**Comment by Smmw** [comment]
Thanks!!! anyway... haha
