### ISSUE TITLE
Failed to get game data from the server

### ISSUE THREAD

**Issue by Drayko** [finndev/PokeBuddy#953]
when i trying to play with my cellphone show me that error
i use the next settings last night:
-6 km/h
-farm
-catch pokemons

I try with others accounts and it works fine but not with this account

**Comment by 404unknown** [comment]
#912

**Comment by xReVoLT-iTheme** [comment]
https://github.com/finndev/PokeBuddy/issues/912

**Comment by WolfKetchum** [comment]
Banned.Forever.
