### ISSUE TITLE
Necrobot error version 0.8.6

### ISSUE THREAD

**Issue by WhosFxith** [finndev/PokeBuddy#959]
I've been having problems with the new version of necrobot.. When i try to log it an error occurs that states: 'Exception caught. writing log buffer' Anyone else has this error or knows how to fix it? if so please respond! Also this might be an easy fix but i'm not that experienced with botting. anyhow hoping to hear from someone soon!

Thanks in advance!

**Comment by rmarquez5** [comment]
I think you're in the wrong forum. I don't think you'll find support for another bot here.

**Comment by RoseCorpse** [comment]
LOL
