### ISSUE TITLE
Potions Problem

### ISSUE THREAD

**Issue by LuzgGO** [finndev/PokeBuddy#97]
The new update is deleting all my potions, Hyper and max potions if I select, "recycle itens", and also is transferring good pokemons with CP 1000+, it tranferred my favorite Clefabe CP 1300 and my growlite, please fix this

**Comment by A-Charvin** [comment]
The issue is still prevailing or is it resolved as of now?

**Comment by LuzgGO** [comment]
its prevailing, I will wait until the next update

**Comment by bfikree** [comment]
Can confirm that it transferred all of my potions and transferred an 1131 Electabuzz

**Comment by Vanethir** [comment]
Potion/Revive transfer should be less aggresive now. Dont know exact number though. So still be careful with a high amount of potions/Revives you might want to keep.

**Comment by Vanethir** [comment]
You can now freely set what (and how many) you want to keep of each item.
