### ISSUE TITLE
Transfer Bad Pokemon is deleting High CP duplicates

### ISSUE THREAD

**Issue by pokemonbotacc** [finndev/PokeBuddy#98]
Seems the newest update is deleting my high CP pokemon if there is more then one, it deletes all but the highest.  This could be a big problem if you have two that your wanting to save and its deletes it. 
For example, if i have 3 Starmi's at 1450, 1440 and 1390 its deleting all but the highest CP.

**Comment by lordofthereef** [comment]
When logged into the game manually, favorite those you never want to lose.

Not that this isn;t something worthy of fixing, but at least you won't lose your prized monsters (for now)> :)

**Comment by pokemonbotacc** [comment]
If they are favorite'd you cant delete? I didn't know that, Ill check it out! Thanks

**Comment by lordofthereef** [comment]
That is correct. As of the newest Pokemon Go update they will not delete.

**Comment by Smmw** [comment]
yes I lost 2 Rapidash, 2 Ninetales, 1 Arcanine and a few Snorlax under 1500cp and greater than 1000cp...

**Comment by juvleo** [comment]
Adding favorite won't work.  The program can delete favorites.

**Comment by YawYawz** [comment]
Is it confirmed that even the Favorite Pokemons will still be delted?

**Comment by Ronixl** [comment]
Yes the bot will still delete pokemon that you put as your favorite.

**Comment by juvleo** [comment]
Yes, it seems it will only leave one strongest of each type.

**Comment by Vanethir** [comment]
Finally it's done. Thank you for your patience. The first version of a list for pokemon evolution and transfer is up to date. You can now freely choose which Pokemon to keep, how many to keep and if you (don't) want to use Eggs for Evolution.

**Comment by Vanethir** [comment]
Kleine wichtige Meldung: Seid noch vorsichtig mit dem Evolution Feature. Da scheint momentan noch ein Fehler drin zu sein.

**Comment by Smmw** [comment]
it is still not working I lost 2 slowbro and 2 arcanine, I definitely chose that do not transfer these two
