### ISSUE TITLE
i cannot see any pokestops, did i get banned? PLease help me!!!!!

### ISSUE THREAD

**Issue by anderchunk** [finndev/PokeBuddy#986]

**Comment by Kokainium** [comment]
Rip

**Comment by anderchunk** [comment]
i cannot see any pokestop if i m using wifi. HOwever, i can see the pokestop with my mobile data. What's going on?

**Comment by Kokainium** [comment]
Try wait for like 30 mins:)

**Comment by luisonator** [comment]
Same here, cant see poke stops and my character dont move, i just see "no pokemon nearby, no pokemon to transfer" in the log section, help :(

**Comment by AlexCtasy** [comment]
Here, i can see all pokestops, catches pokemons, but when i spin a pokestops says like "try later again" is like a softban but well, i hope get unbanned in some hours :S
